In [105]:
import pandas as pd
from datetime import datetime,timedelta
import numpy as np
import matplotlib.pyplot as plt
import xgboost 
from sklearn.metrics import explained_variance_score
from sklearn import metrics
from sklearn.grid_search import GridSearchCV

pd.options.display.max_rows = 300
pd.options.display.max_columns = 100

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

In [4]:
data = pd.read_csv('preprocessed_train.csv')

In [5]:
data[(data['scheduledArrival'].isnull())&(data['actualArrival'].isnull())]

Empty DataFrame
Columns: [runDate, stations, trainCode, trainStationId, scheduledArrival, scheduledDeparture, actualArrival, actualDeparture, distance, dayCount, ArrivalDelay, DepartureDelay]
Index: []

In [6]:
data[(data['scheduledDeparture'].isnull())&(data['actualDeparture'].isnull())]

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay
2495,2020-01-01,BPQ,T-12139,2658211,2020-01-02 09:45:00,NaN,2020-01-02 10:12:00,NaN,891,1,27,0
2541,2020-01-02,BPQ,T-12139,2658211,2020-01-03 09:45:00,NaN,2020-01-03 09:46:00,NaN,891,1,1,0
2575,2020-01-04,BPQ,T-12139,2658211,2020-01-05 09:45:00,NaN,2020-01-05 10:16:00,NaN,891,1,31,0
2621,2020-01-05,BPQ,T-12139,2658211,2020-01-06 09:45:00,NaN,2020-01-06 09:53:00,NaN,891,1,8,0
2657,2020-01-06,BPQ,T-12139,2658211,2020-01-07 09:45:00,NaN,2020-01-07 10:14:00,NaN,891,1,29,0
2703,2020-01-07,BPQ,T-12139,2658211,2020-01-08 09:45:00,NaN,2020-01-08 09:58:00,NaN,891,1,13,0
2747,2020-01-10,BPQ,T-12139,2658211,2020-01-11 09:45:00,NaN,2020-01-11 09:58:00,NaN,891,1,13,0
2792,2020-01-11,BPQ,T-12139,2658211,2020-01-12 09:45:00,NaN,2020-01-12 10:04:00,NaN,891,1,19,0
2838,2020-01-12,BPQ,T-12139,2658211,2020-01-13 09:45:00,NaN,2020-01-13 09:48:00,NaN,891,1,3,0
2883,2020-01-13,BPQ,T-12139,2658211,2020-01-14 09:45:00,NaN,2020-01-14 09:51:00,NaN,891,1,6,0
2929,2020-01-14,BPQ,T-12139,2658211,2020-01-15 09:45:00,NaN,2020-01-15 09:48:00,NaN,891,1,3,0
2974,2020-01-15,BPQ,T-12139,2658211,2020-01-16 09:45:00,NaN,2020-01-16 09:57:00,NaN,891,1,12,0
3020,2020-01-16,BPQ,T-12139,2658211,2020-01-17 09:45:00,NaN,2020-01-17 09:52:00,NaN,891,1,7,0
3056,2020-01-18,BPQ,T-12139,2658211,2020-01-19 09:45:00,NaN,2020-01-19 10:12:00,NaN,891,1,27,0
3102,2020-01-20,BPQ,T-12139,2658211,2020-01-21 09:45:00,NaN,2020-01-21 10:02:00,NaN,891,1,17,0
3148,2020-01-21,BPQ,T-12139,2658211,2020-01-22 09:45:00,NaN,2020-01-22 10:06:00,NaN,891,1,21,0
3194,2020-01-22,BPQ,T-12139,2658211,2020-01-23 09:45:00,NaN,2020-01-23 09:56:00,NaN,891,1,11,0
3233,2020-01-23,BPQ,T-12139,2658211,2020-01-24 09:45:00,NaN,2020-01-24 09:44:00,NaN,891,1,-1,0
3261,2020-01-24,BPQ,T-12139,2658211,2020-01-25 09:45:00,NaN,2020-01-25 10:26:00,NaN,891,1,41,0
3307,2020-01-25,BPQ,T-12139,2658211,2020-01-26 09:45:00,NaN,2020-01-26 09:50:00,NaN,891,1,5,0
3350,2020-01-26,BPQ,T-12139,2658211,2020-01-27 09:45:00,NaN,2020-01-27 10:05:00,NaN,891,1,20,0
3388,2020-01-27,BPQ,T-12139,2658211,2020-01-28 09:45:00,NaN,2020-01-28 10:14:00,NaN,891,1,29,0
3434,2020-01-28,BPQ,T-12139,2658211,2020-01-29 09:45:00,NaN,2020-01-29 09:54:00,NaN,891,1,9,0
3480,2020-01-29,BPQ,T-12139,2658211,2020-01-30 09:45:00,NaN,2020-01-30 09:52:00,NaN,891,1,7,0
3526,2020-01-30,BPQ,T-12139,2658211,2020-01-31 09:45:00,NaN,2020-01-31 09:55:00,NaN,891,1,10,0
3572,2020-01-31,BPQ,T-12139,2658211,2020-02-01 09:45:00,NaN,2020-02-01 09:56:00,NaN,891,1,11,0
3618,2020-02-01,BPQ,T-12139,2658211,2020-02-02 09:45:00,NaN,2020-02-02 09:49:00,NaN,891,1,4,0
3664,2020-02-02,BPQ,T-12139,2658211,2020-02-03 09:45:00,NaN,2020-02-03 09:58:00,NaN,891,1,13,0
3707,2020-02-03,BPQ,T-12139,2658211,2020-02-04 09:45:00,NaN,2020-02-04 10:03:00,NaN,891,1,18,0
3751,2020-02-04,BPQ,T-12139,2658211,2020-02-05 09:45:00,NaN,2020-02-05 10:03:00,NaN,891,1,18,0
3796,2020-02-05,BPQ,T-12139,2658211,2020-02-06 09:45:00,NaN,2020-02-06 10:03:00,NaN,891,1,18,0
3842,2020-02-06,BPQ,T-12139,2658211,2020-02-07 09:45:00,NaN,2020-02-07 09:48:00,NaN,891,1,3,0
3883,2020-02-07,BPQ,T-12139,2658211,2020-02-08 09:45:00,NaN,2020-02-08 10:07:00,NaN,891,1,22,0
3929,2020-02-08,BPQ,T-12139,2658211,2020-02-09 09:45:00,NaN,2020-02-09 09:54:00,NaN,891,1,9,0
3975,2020-02-09,BPQ,T-12139,2658211,2020-02-10 09:45:00,NaN,2020-02-10 09:56:00,NaN,891,1,11,0
4020,2020-02-10,BPQ,T-12139,2658211,2020-02-11 09:45:00,NaN,2020-02-11 10:02:00,NaN,891,1,17,0
4066,2020-02-11,BPQ,T-12139,2658211,2020-02-12 09:45:00,NaN,2020-02-12 10:03:00,NaN,891,1,18,0
4108,2020-02-12,BPQ,T-12139,2658211,2020-02-13 09:45:00,NaN,2020-02-13 10:09:00,NaN,891,1,24,0
4154,2020-02-13,BPQ,T-12139,2658211,2020-02-14 09:45:00,NaN,2020-02-14 09:51:00,NaN,891,1,6,0
4200,2020-02-14,BPQ,T-12139,2658211,2020-02-15 09:45:00,NaN,2020-02-15 09:54:00,NaN,891,1,9,0
4246,2020-02-15,BPQ,T-12139,2658211,2020-02-16 09:45:00,NaN,2020-02-16 09:58:00,NaN,891,1,13,0
4292,2020-02-16,BPQ,T-12139,2658211,2020-02-17 09:45:00,NaN,2020-02-17 09:53:00,NaN,891,1,8,0
4337,2020-02-18,BPQ,T-12139,2658211,2020-02-19 09:45:00,NaN,2020-02-19 09:58:00,NaN,891,1,13,0
4383,2020-02-19,BPQ,T-12139,2658211,2020-02-20 09:45:00,NaN,2020-02-20 10:00:00,NaN,891,1,15,0
14431,2020-01-22,NDLS,T-12625,2657756,2020-01-24 13:45:00,NaN,2020-01-24 14:13:00,NaN,3031,2,28,0
14514,2020-01-24,NDLS,T-12625,2657756,2020-01-26 13:45:00,NaN,2020-01-26 14:00:00,NaN,3031,2,15,0
14555,2020-01-25,NDLS,T-12625,2657756,2020-01-27 13:45:00,NaN,2020-01-27 13:54:00,NaN,3031,2,9,0
14598,2020-01-26,NDLS,T-12625,2657756,2020-01-28 13:45:00,NaN,2020-01-28 13:36:00,NaN,3031,2,-9,0
14640,2020-01-27,NDLS,T-12625,2657756,2020-01-29 13:45:00,NaN,2020-01-29 13:57:00,NaN,3031,2,12,0
27902,2020-01-01,KLK,T-12925,2658088,2020-01-02 16:45:00,NaN,2020-01-02 17:40:00,NaN,1676,1,55,55
27946,2020-01-02,KLK,T-12925,2658088,2020-01-03 16:45:00,NaN,2020-01-03 17:08:00,NaN,1676,1,23,23
27990,2020-01-03,KLK,T-12925,2658088,2020-01-04 16:45:00,NaN,2020-01-04 17:37:00,NaN,1676,1,52,52
28027,2020-01-04,KLK,T-12925,2658088,2020-01-05 16:45:00,NaN,2020-01-05 17:53:00,NaN,1676,1,68,68
28069,2020-01-05,KLK,T-12925,2658088,2020-01-06 16:45:00,NaN,2020-01-06 17:14:00,NaN,1676,1,29,29
28113,2020-01-06,KLK,T-12925,2658088,2020-01-07 16:45:00,NaN,2020-01-07 16:54:00,NaN,1676,1,9,9
28156,2020-01-08,KLK,T-12925,2658088,2020-01-09 16:45:00,NaN,2020-01-09 16:50:00,NaN,1676,1,5,4
28227,2020-01-10,KLK,T-12925,2658088,2020-01-11 16:45:00,NaN,2020-01-11 16:54:00,NaN,1676,1,9,9
28271,2020-01-11,KLK,T-12925,2658088,2020-01-12 16:45:00,NaN,2020-01-12 16:56:00,NaN,1676,1,11,11
28314,2020-01-12,KLK,T-12925,2658088,2020-01-13 16:45:00,NaN,2020-01-13 16:57:00,NaN,1676,1,12,12
28355,2020-01-13,KLK,T-12925,2658088,2020-01-14 16:45:00,NaN,2020-01-14 18:04:00,NaN,1676,1,79,79
28399,2020-01-14,KLK,T-12925,2658088,2020-01-15 16:45:00,NaN,2020-01-15 17:12:00,NaN,1676,1,27,28
28442,2020-01-15,KLK,T-12925,2658088,2020-01-16 16:45:00,NaN,2020-01-16 17:21:00,NaN,1676,1,36,36
28486,2020-01-17,KLK,T-12925,2658088,2020-01-18 16:45:00,NaN,2020-01-18 17:47:00,NaN,1676,1,62,62
28529,2020-01-18,KLK,T-12925,2658088,2020-01-19 16:45:00,NaN,2020-01-19 17:51:00,NaN,1676,1,66,66
28565,2020-01-20,KLK,T-12925,2658088,2020-01-21 16:45:00,NaN,2020-01-21 18:04:00,NaN,1676,1,79,78
28671,2020-01-23,KLK,T-12925,2658088,2020-01-24 16:45:00,NaN,2020-01-24 17:05:00,NaN,1676,1,20,20
28715,2020-01-24,KLK,T-12925,2658088,2020-01-25 16:45:00,NaN,2020-01-25 16:56:00,NaN,1676,1,11,11
28758,2020-01-26,KLK,T-12925,2658088,2020-01-27 16:45:00,NaN,2020-01-27 17:24:00,NaN,1676,1,39,38
28802,2020-01-27,KLK,T-12925,2658088,2020-01-28 16:45:00,NaN,2020-01-28 16:50:00,NaN,1676,1,5,6
28845,2020-01-29,KLK,T-12925,2658088,2020-01-30 16:45:00,NaN,2020-01-30 17:24:00,NaN,1676,1,39,40
28889,2020-01-30,KLK,T-12925,2658088,2020-01-31 16:45:00,NaN,2020-01-31 17:14:00,NaN,1676,1,29,29
28933,2020-01-31,KLK,T-12925,2658088,2020-02-01 16:45:00,NaN,2020-02-01 17:08:00,NaN,1676,1,23,22
28977,2020-02-02,KLK,T-12925,2658088,2020-02-03 16:45:00,NaN,2020-02-03 17:15:00,NaN,1676,1,30,30
29020,2020-02-03,KLK,T-12925,2658088,2020-02-04 16:45:00,NaN,2020-02-04 16:59:00,NaN,1676,1,14,14
29063,2020-02-04,KLK,T-12925,2658088,2020-02-05 16:45:00,NaN,2020-02-05 17:10:00,NaN,1676,1,25,25
29142,2020-02-06,KLK,T-12925,2658088,2020-02-07 16:45:00,NaN,2020-02-07 16:59:00,NaN,1676,1,14,14
29186,2020-02-08,KLK,T-12925,2658088,2020-02-09 16:45:00,NaN,2020-02-09 17:06:00,NaN,1676,1,21,22
29229,2020-02-09,KLK,T-12925,2658088,2020-02-10 16:45:00,NaN,2020-02-10 16:56:00,NaN,1676,1,11,11
29271,2020-02-10,KLK,T-12925,2658088,2020-02-11 16:45:00,NaN,2020-02-11 17:08:00,NaN,1676,1,23,23
29314,2020-02-11,KLK,T-12925,2658088,2020-02-12 16:45:00,NaN,2020-02-12 17:04:00,NaN,1676,1,19,19
29357,2020-02-12,KLK,T-12925,2658088,2020-02-13 16:45:00,NaN,2020-02-13 18:05:00,NaN,1676,1,80,80
29400,2020-02-13,KLK,T-12925,2658088,2020-02-14 16:45:00,NaN,2020-02-14 17:03:00,NaN,1676,1,18,18
29444,2020-02-14,KLK,T-12925,2658088,2020-02-15 16:45:00,NaN,2020-02-15 16:56:00,NaN,1676,1,11,11
29487,2020-02-16,KLK,T-12925,2658088,2020-02-17 16:45:00,NaN,2020-02-17 17:44:00,NaN,1676,1,59,59
29531,2020-02-18,KLK,T-12925,2658088,2020-02-19 16:45:00,NaN,2020-02-19 17:22:00,NaN,1676,1,37,38
29574,2020-02-19,KLK,T-12925,2658088,2020-02-20 16:45:00,NaN,2020-02-20 18:06:00,NaN,1676,1,81,81

In [7]:
data[(data['scheduledDeparture'].isnull())&(data['scheduledArrival'].isnull())]

Empty DataFrame
Columns: [runDate, stations, trainCode, trainStationId, scheduledArrival, scheduledDeparture, actualArrival, actualDeparture, distance, dayCount, ArrivalDelay, DepartureDelay]
Index: []

In [8]:
data.scheduledArrival[0]

nan

In [9]:
data['runDate']= pd.to_datetime(data['runDate'])
data['scheduledArrival']= pd.to_datetime(data['scheduledArrival'])
data['scheduledDeparture']= pd.to_datetime(data['scheduledDeparture'])
data['actualArrival']= pd.to_datetime(data['actualArrival'])
data['actualDeparture']= pd.to_datetime(data['actualDeparture'])

In [10]:
type(data.scheduledArrival[0])==pd._libs.tslibs.nattype.NaTType

True

## Correcting values in scheduled departure column

In [11]:
def correct_scheduled_arrival(x):
    if (type(x[0])==pd._libs.tslibs.nattype.NaTType) or (type(x[1])==pd._libs.tslibs.nattype.NaTType):
        return x[0]
    
    elif x[0] > x[1]:
        x[0] = x[0] - timedelta(days=1)
    return x[0]

In [12]:
data['scheduledArrival'] = data[['scheduledArrival','scheduledDeparture']].apply(lambda x:correct_scheduled_arrival(x),axis=1)

In [13]:
data[data.scheduledArrival>data.scheduledDeparture]

Empty DataFrame
Columns: [runDate, stations, trainCode, trainStationId, scheduledArrival, scheduledDeparture, actualArrival, actualDeparture, distance, dayCount, ArrivalDelay, DepartureDelay]
Index: []

In [14]:
data.isnull().sum()

runDate                 0
stations                0
trainCode               0
trainStationId          0
scheduledArrival      689
scheduledDeparture    673
actualArrival           0
actualDeparture        86
distance                0
dayCount                0
ArrivalDelay            0
DepartureDelay          0
dtype: int64

In [15]:
data[data.actualDeparture.isnull()]

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay
2495,2020-01-01,BPQ,T-12139,2658211,2020-01-02 09:45:00,NaT,2020-01-02 10:12:00,NaT,891,1,27,0
2541,2020-01-02,BPQ,T-12139,2658211,2020-01-03 09:45:00,NaT,2020-01-03 09:46:00,NaT,891,1,1,0
2575,2020-01-04,BPQ,T-12139,2658211,2020-01-05 09:45:00,NaT,2020-01-05 10:16:00,NaT,891,1,31,0
2621,2020-01-05,BPQ,T-12139,2658211,2020-01-06 09:45:00,NaT,2020-01-06 09:53:00,NaT,891,1,8,0
2657,2020-01-06,BPQ,T-12139,2658211,2020-01-07 09:45:00,NaT,2020-01-07 10:14:00,NaT,891,1,29,0
2703,2020-01-07,BPQ,T-12139,2658211,2020-01-08 09:45:00,NaT,2020-01-08 09:58:00,NaT,891,1,13,0
2747,2020-01-10,BPQ,T-12139,2658211,2020-01-11 09:45:00,NaT,2020-01-11 09:58:00,NaT,891,1,13,0
2792,2020-01-11,BPQ,T-12139,2658211,2020-01-12 09:45:00,NaT,2020-01-12 10:04:00,NaT,891,1,19,0
2838,2020-01-12,BPQ,T-12139,2658211,2020-01-13 09:45:00,NaT,2020-01-13 09:48:00,NaT,891,1,3,0
2883,2020-01-13,BPQ,T-12139,2658211,2020-01-14 09:45:00,NaT,2020-01-14 09:51:00,NaT,891,1,6,0
2929,2020-01-14,BPQ,T-12139,2658211,2020-01-15 09:45:00,NaT,2020-01-15 09:48:00,NaT,891,1,3,0
2974,2020-01-15,BPQ,T-12139,2658211,2020-01-16 09:45:00,NaT,2020-01-16 09:57:00,NaT,891,1,12,0
3020,2020-01-16,BPQ,T-12139,2658211,2020-01-17 09:45:00,NaT,2020-01-17 09:52:00,NaT,891,1,7,0
3056,2020-01-18,BPQ,T-12139,2658211,2020-01-19 09:45:00,NaT,2020-01-19 10:12:00,NaT,891,1,27,0
3102,2020-01-20,BPQ,T-12139,2658211,2020-01-21 09:45:00,NaT,2020-01-21 10:02:00,NaT,891,1,17,0
3148,2020-01-21,BPQ,T-12139,2658211,2020-01-22 09:45:00,NaT,2020-01-22 10:06:00,NaT,891,1,21,0
3194,2020-01-22,BPQ,T-12139,2658211,2020-01-23 09:45:00,NaT,2020-01-23 09:56:00,NaT,891,1,11,0
3233,2020-01-23,BPQ,T-12139,2658211,2020-01-24 09:45:00,NaT,2020-01-24 09:44:00,NaT,891,1,-1,0
3261,2020-01-24,BPQ,T-12139,2658211,2020-01-25 09:45:00,NaT,2020-01-25 10:26:00,NaT,891,1,41,0
3307,2020-01-25,BPQ,T-12139,2658211,2020-01-26 09:45:00,NaT,2020-01-26 09:50:00,NaT,891,1,5,0
3350,2020-01-26,BPQ,T-12139,2658211,2020-01-27 09:45:00,NaT,2020-01-27 10:05:00,NaT,891,1,20,0
3388,2020-01-27,BPQ,T-12139,2658211,2020-01-28 09:45:00,NaT,2020-01-28 10:14:00,NaT,891,1,29,0
3434,2020-01-28,BPQ,T-12139,2658211,2020-01-29 09:45:00,NaT,2020-01-29 09:54:00,NaT,891,1,9,0
3480,2020-01-29,BPQ,T-12139,2658211,2020-01-30 09:45:00,NaT,2020-01-30 09:52:00,NaT,891,1,7,0
3526,2020-01-30,BPQ,T-12139,2658211,2020-01-31 09:45:00,NaT,2020-01-31 09:55:00,NaT,891,1,10,0
3572,2020-01-31,BPQ,T-12139,2658211,2020-02-01 09:45:00,NaT,2020-02-01 09:56:00,NaT,891,1,11,0
3618,2020-02-01,BPQ,T-12139,2658211,2020-02-02 09:45:00,NaT,2020-02-02 09:49:00,NaT,891,1,4,0
3664,2020-02-02,BPQ,T-12139,2658211,2020-02-03 09:45:00,NaT,2020-02-03 09:58:00,NaT,891,1,13,0
3707,2020-02-03,BPQ,T-12139,2658211,2020-02-04 09:45:00,NaT,2020-02-04 10:03:00,NaT,891,1,18,0
3751,2020-02-04,BPQ,T-12139,2658211,2020-02-05 09:45:00,NaT,2020-02-05 10:03:00,NaT,891,1,18,0
3796,2020-02-05,BPQ,T-12139,2658211,2020-02-06 09:45:00,NaT,2020-02-06 10:03:00,NaT,891,1,18,0
3842,2020-02-06,BPQ,T-12139,2658211,2020-02-07 09:45:00,NaT,2020-02-07 09:48:00,NaT,891,1,3,0
3883,2020-02-07,BPQ,T-12139,2658211,2020-02-08 09:45:00,NaT,2020-02-08 10:07:00,NaT,891,1,22,0
3929,2020-02-08,BPQ,T-12139,2658211,2020-02-09 09:45:00,NaT,2020-02-09 09:54:00,NaT,891,1,9,0
3975,2020-02-09,BPQ,T-12139,2658211,2020-02-10 09:45:00,NaT,2020-02-10 09:56:00,NaT,891,1,11,0
4020,2020-02-10,BPQ,T-12139,2658211,2020-02-11 09:45:00,NaT,2020-02-11 10:02:00,NaT,891,1,17,0
4066,2020-02-11,BPQ,T-12139,2658211,2020-02-12 09:45:00,NaT,2020-02-12 10:03:00,NaT,891,1,18,0
4108,2020-02-12,BPQ,T-12139,2658211,2020-02-13 09:45:00,NaT,2020-02-13 10:09:00,NaT,891,1,24,0
4154,2020-02-13,BPQ,T-12139,2658211,2020-02-14 09:45:00,NaT,2020-02-14 09:51:00,NaT,891,1,6,0
4200,2020-02-14,BPQ,T-12139,2658211,2020-02-15 09:45:00,NaT,2020-02-15 09:54:00,NaT,891,1,9,0
4246,2020-02-15,BPQ,T-12139,2658211,2020-02-16 09:45:00,NaT,2020-02-16 09:58:00,NaT,891,1,13,0
4292,2020-02-16,BPQ,T-12139,2658211,2020-02-17 09:45:00,NaT,2020-02-17 09:53:00,NaT,891,1,8,0
4337,2020-02-18,BPQ,T-12139,2658211,2020-02-19 09:45:00,NaT,2020-02-19 09:58:00,NaT,891,1,13,0
4383,2020-02-19,BPQ,T-12139,2658211,2020-02-20 09:45:00,NaT,2020-02-20 10:00:00,NaT,891,1,15,0
14431,2020-01-22,NDLS,T-12625,2657756,2020-01-24 13:45:00,NaT,2020-01-24 14:13:00,NaT,3031,2,28,0
14514,2020-01-24,NDLS,T-12625,2657756,2020-01-26 13:45:00,NaT,2020-01-26 14:00:00,NaT,3031,2,15,0
14555,2020-01-25,NDLS,T-12625,2657756,2020-01-27 13:45:00,NaT,2020-01-27 13:54:00,NaT,3031,2,9,0
14598,2020-01-26,NDLS,T-12625,2657756,2020-01-28 13:45:00,NaT,2020-01-28 13:36:00,NaT,3031,2,-9,0
14640,2020-01-27,NDLS,T-12625,2657756,2020-01-29 13:45:00,NaT,2020-01-29 13:57:00,NaT,3031,2,12,0
27902,2020-01-01,KLK,T-12925,2658088,2020-01-02 16:45:00,NaT,2020-01-02 17:40:00,NaT,1676,1,55,55
27946,2020-01-02,KLK,T-12925,2658088,2020-01-03 16:45:00,NaT,2020-01-03 17:08:00,NaT,1676,1,23,23
27990,2020-01-03,KLK,T-12925,2658088,2020-01-04 16:45:00,NaT,2020-01-04 17:37:00,NaT,1676,1,52,52
28027,2020-01-04,KLK,T-12925,2658088,2020-01-05 16:45:00,NaT,2020-01-05 17:53:00,NaT,1676,1,68,68
28069,2020-01-05,KLK,T-12925,2658088,2020-01-06 16:45:00,NaT,2020-01-06 17:14:00,NaT,1676,1,29,29
28113,2020-01-06,KLK,T-12925,2658088,2020-01-07 16:45:00,NaT,2020-01-07 16:54:00,NaT,1676,1,9,9
28156,2020-01-08,KLK,T-12925,2658088,2020-01-09 16:45:00,NaT,2020-01-09 16:50:00,NaT,1676,1,5,4
28227,2020-01-10,KLK,T-12925,2658088,2020-01-11 16:45:00,NaT,2020-01-11 16:54:00,NaT,1676,1,9,9
28271,2020-01-11,KLK,T-12925,2658088,2020-01-12 16:45:00,NaT,2020-01-12 16:56:00,NaT,1676,1,11,11
28314,2020-01-12,KLK,T-12925,2658088,2020-01-13 16:45:00,NaT,2020-01-13 16:57:00,NaT,1676,1,12,12
28355,2020-01-13,KLK,T-12925,2658088,2020-01-14 16:45:00,NaT,2020-01-14 18:04:00,NaT,1676,1,79,79
28399,2020-01-14,KLK,T-12925,2658088,2020-01-15 16:45:00,NaT,2020-01-15 17:12:00,NaT,1676,1,27,28
28442,2020-01-15,KLK,T-12925,2658088,2020-01-16 16:45:00,NaT,2020-01-16 17:21:00,NaT,1676,1,36,36
28486,2020-01-17,KLK,T-12925,2658088,2020-01-18 16:45:00,NaT,2020-01-18 17:47:00,NaT,1676,1,62,62
28529,2020-01-18,KLK,T-12925,2658088,2020-01-19 16:45:00,NaT,2020-01-19 17:51:00,NaT,1676,1,66,66
28565,2020-01-20,KLK,T-12925,2658088,2020-01-21 16:45:00,NaT,2020-01-21 18:04:00,NaT,1676,1,79,78
28671,2020-01-23,KLK,T-12925,2658088,2020-01-24 16:45:00,NaT,2020-01-24 17:05:00,NaT,1676,1,20,20
28715,2020-01-24,KLK,T-12925,2658088,2020-01-25 16:45:00,NaT,2020-01-25 16:56:00,NaT,1676,1,11,11
28758,2020-01-26,KLK,T-12925,2658088,2020-01-27 16:45:00,NaT,2020-01-27 17:24:00,NaT,1676,1,39,38
28802,2020-01-27,KLK,T-12925,2658088,2020-01-28 16:45:00,NaT,2020-01-28 16:50:00,NaT,1676,1,5,6
28845,2020-01-29,KLK,T-12925,2658088,2020-01-30 16:45:00,NaT,2020-01-30 17:24:00,NaT,1676,1,39,40
28889,2020-01-30,KLK,T-12925,2658088,2020-01-31 16:45:00,NaT,2020-01-31 17:14:00,NaT,1676,1,29,29
28933,2020-01-31,KLK,T-12925,2658088,2020-02-01 16:45:00,NaT,2020-02-01 17:08:00,NaT,1676,1,23,22
28977,2020-02-02,KLK,T-12925,2658088,2020-02-03 16:45:00,NaT,2020-02-03 17:15:00,NaT,1676,1,30,30
29020,2020-02-03,KLK,T-12925,2658088,2020-02-04 16:45:00,NaT,2020-02-04 16:59:00,NaT,1676,1,14,14
29063,2020-02-04,KLK,T-12925,2658088,2020-02-05 16:45:00,NaT,2020-02-05 17:10:00,NaT,1676,1,25,25
29142,2020-02-06,KLK,T-12925,2658088,2020-02-07 16:45:00,NaT,2020-02-07 16:59:00,NaT,1676,1,14,14
29186,2020-02-08,KLK,T-12925,2658088,2020-02-09 16:45:00,NaT,2020-02-09 17:06:00,NaT,1676,1,21,22
29229,2020-02-09,KLK,T-12925,2658088,2020-02-10 16:45:00,NaT,2020-02-10 16:56:00,NaT,1676,1,11,11
29271,2020-02-10,KLK,T-12925,2658088,2020-02-11 16:45:00,NaT,2020-02-11 17:08:00,NaT,1676,1,23,23
29314,2020-02-11,KLK,T-12925,2658088,2020-02-12 16:45:00,NaT,2020-02-12 17:04:00,NaT,1676,1,19,19
29357,2020-02-12,KLK,T-12925,2658088,2020-02-13 16:45:00,NaT,2020-02-13 18:05:00,NaT,1676,1,80,80
29400,2020-02-13,KLK,T-12925,2658088,2020-02-14 16:45:00,NaT,2020-02-14 17:03:00,NaT,1676,1,18,18
29444,2020-02-14,KLK,T-12925,2658088,2020-02-15 16:45:00,NaT,2020-02-15 16:56:00,NaT,1676,1,11,11
29487,2020-02-16,KLK,T-12925,2658088,2020-02-17 16:45:00,NaT,2020-02-17 17:44:00,NaT,1676,1,59,59
29531,2020-02-18,KLK,T-12925,2658088,2020-02-19 16:45:00,NaT,2020-02-19 17:22:00,NaT,1676,1,37,38
29574,2020-02-19,KLK,T-12925,2658088,2020-02-20 16:45:00,NaT,2020-02-20 18:06:00,NaT,1676,1,81,81

In [16]:
data.head(100)

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay
0,2020-01-01,FZR,T-12138,2657812,NaT,2020-01-01 21:40:00,2020-01-01 00:00:00,2020-01-01 21:40:00,0,0,0,0
1,2020-01-01,FDK,T-12138,2659393,2020-01-01 22:05:00,2020-01-01 22:07:00,2020-01-01 22:16:00,2020-01-01 22:18:00,32,0,11,11
2,2020-01-01,KKP,T-12138,2658108,2020-01-01 22:23:00,2020-01-01 22:25:00,2020-01-01 22:37:00,2020-01-01 22:38:00,45,0,14,13
3,2020-01-01,GJUT,T-12138,2734206,2020-01-01 22:38:00,2020-01-01 22:40:00,2020-01-01 22:56:00,2020-01-01 22:57:00,61,0,18,17
4,2020-01-01,GNA,T-12138,2742572,2020-01-01 22:54:00,2020-01-01 22:56:00,2020-01-01 23:14:00,2020-01-01 23:15:00,76,0,20,19
5,2020-01-01,BTI,T-12138,2657716,2020-01-01 23:25:00,2020-01-01 23:50:00,2020-01-01 23:31:00,2020-01-01 23:51:00,88,0,6,1
6,2020-01-01,MAUR,T-12138,2658362,2020-01-02 00:14:00,2020-01-02 00:16:00,2020-01-02 00:25:00,2020-01-02 00:27:00,122,1,11,11
7,2020-01-01,MSZ,T-12138,2659151,2020-01-02 00:31:00,2020-01-02 00:33:00,2020-01-02 00:46:00,2020-01-02 00:48:00,140,1,15,15
8,2020-01-01,BLZ,T-12138,2658107,2020-01-02 00:47:00,2020-01-02 00:49:00,2020-01-02 01:02:00,2020-01-02 01:04:00,156,1,15,15
9,2020-01-01,BRZ,T-12138,2733490,2020-01-02 01:02:00,2020-01-02 01:04:00,2020-01-02 01:17:00,2020-01-02 01:19:00,172,1,15,15
10,2020-01-01,JHL,T-12138,2659348,2020-01-02 01:21:00,2020-01-02 01:23:00,2020-01-02 01:30:00,2020-01-02 01:32:00,186,1,9,9
11,2020-01-01,TUN,T-12138,2657804,2020-01-02 01:33:00,2020-01-02 01:35:00,2020-01-02 01:44:00,2020-01-02 01:46:00,198,1,11,11
12,2020-01-01,NRW,T-12138,2659565,2020-01-02 01:54:00,2020-01-02 01:56:00,2020-01-02 02:05:00,2020-01-02 02:07:00,224,1,11,11
13,2020-01-01,JIND,T-12138,2658192,2020-01-02 02:25:00,2020-01-02 02:28:00,2020-01-02 02:28:00,2020-01-02 02:30:00,258,1,3,2
14,2020-01-01,ROK,T-12138,2659284,2020-01-02 03:10:00,2020-01-02 03:12:00,2020-01-02 03:08:00,2020-01-02 03:14:00,315,1,-2,2
15,2020-01-01,BGZ,T-12138,2657989,2020-01-02 03:38:00,2020-01-02 03:40:00,2020-01-02 03:39:00,2020-01-02 03:42:00,355,1,1,2
16,2020-01-01,DKZ,T-12138,2659013,2020-01-02 04:33:00,2020-01-02 04:35:00,2020-01-02 04:35:00,2020-01-02 04:37:00,382,1,2,2
17,2020-01-01,NDLS,T-12138,2657756,2020-01-02 05:00:00,2020-01-02 05:15:00,2020-01-02 04:55:00,2020-01-02 05:15:00,386,1,-5,0
18,2020-01-01,FDB,T-12138,2659398,2020-01-02 05:41:00,2020-01-02 05:43:00,2020-01-02 05:45:00,2020-01-02 05:47:00,414,1,4,4
19,2020-01-01,KSV,T-12138,2734622,2020-01-02 06:57:00,2020-01-02 06:59:00,2020-01-02 06:47:00,2020-01-02 07:10:00,486,1,-10,11
20,2020-01-01,MTJ,T-12138,2659144,2020-01-02 07:38:00,2020-01-02 07:40:00,2020-01-02 07:52:00,2020-01-02 07:57:00,527,1,14,17
21,2020-01-01,RKM,T-12138,2659326,2020-01-02 08:14:00,2020-01-02 08:16:00,2020-01-02 08:38:00,2020-01-02 08:40:00,577,1,24,24
22,2020-01-01,AGC,T-12138,2657986,2020-01-02 08:30:00,2020-01-02 08:35:00,2020-01-02 08:49:00,2020-01-02 08:58:00,581,1,19,23
23,2020-01-01,DHO,T-12138,2659095,2020-01-02 09:25:00,2020-01-02 09:27:00,2020-01-02 09:35:00,2020-01-02 09:39:00,634,1,10,12
24,2020-01-01,MRA,T-12138,2659193,2020-01-02 09:53:00,2020-01-02 09:55:00,2020-01-02 10:05:00,2020-01-02 10:13:00,661,1,12,18
25,2020-01-01,GWL,T-12138,2658454,2020-01-02 10:35:00,2020-01-02 10:40:00,2020-01-02 10:51:00,2020-01-02 10:56:00,699,1,16,16
26,2020-01-01,DBA,T-12138,2658414,2020-01-02 11:15:00,2020-01-02 11:17:00,2020-01-02 11:34:00,2020-01-02 11:36:00,741,1,19,19
27,2020-01-01,DAA,T-12138,2658432,2020-01-02 11:38:00,2020-01-02 11:40:00,2020-01-02 12:05:00,2020-01-02 12:07:00,772,1,27,27
28,2020-01-01,JHS,T-12138,2659350,2020-01-02 12:25:00,2020-01-02 12:35:00,2020-01-02 12:40:00,2020-01-02 12:50:00,797,1,15,15
29,2020-01-01,BAB,T-12138,2657894,2020-01-02 13:00:00,2020-01-02 13:02:00,2020-01-02 13:18:00,2020-01-02 13:57:00,822,1,18,55
30,2020-01-01,LAR,T-12138,2658398,2020-01-02 13:47:00,2020-01-02 13:49:00,2020-01-02 15:08:00,2020-01-02 15:18:00,887,1,81,89
31,2020-01-01,BINA,T-12138,2657929,2020-01-02 14:45:00,2020-01-02 14:50:00,2020-01-02 16:30:00,2020-01-02 16:36:00,950,1,105,106
32,2020-01-01,BAQ,T-12138,2657881,2020-01-02 15:23:00,2020-01-02 15:25:00,2020-01-02 17:13:00,2020-01-02 17:15:00,996,1,110,110
33,2020-01-01,BHS,T-12138,2658012,2020-01-02 15:52:00,2020-01-02 15:54:00,2020-01-02 17:53:00,2020-01-02 17:55:00,1035,1,121,121
34,2020-01-01,BPL,T-12138,2658194,2020-01-02 16:50:00,2020-01-02 16:55:00,2020-01-02 19:03:00,2020-01-02 19:09:00,1088,1,133,134
35,2020-01-01,HBJ,T-12138,2658440,2020-01-02 17:07:00,2020-01-02 17:09:00,2020-01-02 19:20:00,2020-01-02 19:24:00,1095,1,133,135
36,2020-01-01,HBD,T-12138,2658443,2020-01-02 18:13:00,2020-01-02 18:15:00,2020-01-02 20:35:00,2020-01-02 20:37:00,1162,1,142,142
37,2020-01-01,ET,T-12138,2658804,2020-01-02 18:40:00,2020-01-02 18:46:00,2020-01-02 21:03:00,2020-01-02 21:16:00,1180,1,143,150
38,2020-01-01,BPF,T-12138,2731917,2020-01-02 19:13:00,2020-01-02 19:15:00,2020-01-02 21:48:00,2020-01-02 21:50:00,1214,1,155,155
39,2020-01-01,HD,T-12138,2658940,2020-01-02 19:43:00,2020-01-02 19:45:00,2020-01-02 22:19:00,2020-01-02 22:21:00,1256,1,156,156
40,2020-01-01,KKN,T-12138,2731952,2020-01-02 20:10:00,2020-01-02 20:12:00,2020-01-02 22:45:00,2020-01-02 22:47:00,1288,1,155,155
41,2020-01-01,KNW,T-12138,2658041,2020-01-02 21:35:00,2020-01-02 21:40:00,2020-01-02 23:36:00,2020-01-02 23:41:00,1364,1,121,121
42,2020-01-01,BAU,T-12138,2657885,2020-01-02 22:28:00,2020-01-02 22:30:00,2020-01-03 00:29:00,2020-01-03 00:30:00,1433,1,121,120
43,2020-01-01,BSL,T-12138,2657664,2020-01-02 23:30:00,2020-01-02 23:35:00,2020-01-03 01:21:00,2020-01-03 01:31:00,1487,1,111,116
44,2020-01-01,JL,T-12138,2658959,2020-01-02 23:59:00,2020-01-03 00:01:00,2020-01-03 02:04:00,2020-01-03 02:08:00,1511,2,125,127
45,2020-01-01,CSN,T-12138,2658714,2020-01-03 00:59:00,2020-01-03 01:01:00,2020-01-03 03:24:00,2020-01-03 03:26:00,1604,2,145,145
46,2020-01-01,MMR,T-12138,2658996,2020-01-03 01:50:00,2020-01-03 01:55:00,2020-01-03 04:37:00,2020-01-03 04:42:00,1671,2,167,167
47,2020-01-01,NK,T-12138,2658902,2020-01-03 02:45:00,2020-01-03 02:50:00,2020-01-03 05:27:00,2020-01-03 05:30:00,1744,2,162,160
48,2020-01-01,DVL,T-12138,2733304,2020-01-03 02:58:00,2020-01-03 03:00:00,2020-01-03 05:38:00,2020-01-03 05:40:00,1750,2,160,160
49,2020-01-01,IGP,T-12138,2658818,2020-01-03 04:25:00,2020-01-03 04:30:00,2020-01-03 06:21:00,2020-01-03 06:31:00,1795,2,116,121
50,2020-01-02,FZR,T-12138,2657812,NaT,2020-01-02 21:40:00,2020-01-02 00:00:00,2020-01-02 21:40:00,0,0,0,0
51,2020-01-02,FDK,T-12138,2659393,2020-01-02 22:05:00,2020-01-02 22:07:00,2020-01-02 22:14:00,2020-01-02 22:17:00,32,0,9,10
52,2020-01-02,KKP,T-12138,2658108,2020-01-02 22:23:00,2020-01-02 22:25:00,2020-01-02 22:34:00,2020-01-02 22:36:00,45,0,11,11
53,2020-01-02,GJUT,T-12138,2734206,2020-01-02 22:38:00,2020-01-02 22:40:00,2020-01-02 22:51:00,2020-01-02 22:52:00,61,0,13,12
54,2020-01-02,GNA,T-12138,2742572,2020-01-02 22:54:00,2020-01-02 22:56:00,2020-01-02 23:06:00,2020-01-02 23:07:00,76,0,12,11
55,2020-01-02,BTI,T-12138,2657716,2020-01-02 23:25:00,2020-01-02 23:50:00,2020-01-02 23:23:00,2020-01-02 23:52:00,88,0,-2,2
56,2020-01-02,MAUR,T-12138,2658362,2020-01-03 00:14:00,2020-01-03 00:16:00,2020-01-03 00:25:00,2020-01-03 00:26:00,122,1,11,10
57,2020-01-02,MSZ,T-12138,2659151,2020-01-03 00:31:00,2020-01-03 00:33:00,2020-01-03 00:42:00,2020-01-03 00:44:00,140,1,11,11
58,2020-01-02,BLZ,T-12138,2658107,2020-01-03 00:47:00,2020-01-03 00:49:00,2020-01-03 00:59:00,2020-01-03 01:01:00,156,1,12,12
59,2020-01-02,BRZ,T-12138,2733490,2020-01-03 01:02:00,2020-01-03 01:04:00,2020-01-03 01:15:00,2020-01-03 01:17:00,172,1,13,13
60,2020-01-02,JHL,T-12138,2659348,2020-01-03 01:21:00,2020-01-03 01:23:00,2020-01-03 01:33:00,2020-01-03 01:46:00,186,1,12,23
61,2020-01-02,TUN,T-12138,2657804,2020-01-03 01:33:00,2020-01-03 01:35:00,2020-01-03 01:58:00,2020-01-03 02:00:00,198,1,25,25
62,2020-01-02,NRW,T-12138,2659565,2020-01-03 01:54:00,2020-01-03 01:56:00,2020-01-03 02:18:00,2020-01-03 02:20:00,224,1,24,24
63,2020-01-02,JIND,T-12138,2658192,2020-01-03 02:25:00,2020-01-03 02:28:00,2020-01-03 02:44:00,2020-01-03 02:46:00,258,1,19,18
64,2020-01-02,ROK,T-12138,2659284,2020-01-03 03:10:00,2020-01-03 03:12:00,2020-01-03 03:23:00,2020-01-03 03:25:00,315,1,13,13
65,2020-01-02,BGZ,T-12138,2657989,2020-01-03 03:38:00,2020-01-03 03:40:00,2020-01-03 03:52:00,2020-01-03 03:54:00,355,1,14,14
66,2020-01-02,SSB,T-12138,2658315,2020-01-03 04:18:00,2020-01-03 04:20:00,2020-01-03 04:11:00,2020-01-03 04:22:00,374,1,-7,2
67,2020-01-02,DKZ,T-12138,2659013,2020-01-03 04:33:00,2020-01-03 04:35:00,2020-01-03 04:35:00,2020-01-03 04:37:00,382,1,2,2
68,2020-01-02,NDLS,T-12138,2657756,2020-01-03 05:00:00,2020-01-03 05:15:00,2020-01-03 04:53:00,2020-01-03 05:15:00,386,1,-7,0
69,2020-01-02,FDB,T-12138,2659398,2020-01-03 05:41:00,2020-01-03 05:43:00,2020-01-03 05:45:00,2020-01-03 05:46:00,414,1,4,3
70,2020-01-02,KSV,T-12138,2734622,2020-01-03 06:57:00,2020-01-03 06:59:00,2020-01-03 06:58:00,2020-01-03 07:03:00,486,1,1,4
71,2020-01-02,MTJ,T-12138,2659144,2020-01-03 07:38:00,2020-01-03 07:40:00,2020-01-03 07:47:00,2020-01-03 07:51:00,527,1,9,11
72,2020-01-02,RKM,T-12138,2659326,2020-01-03 08:14:00,2020-01-03 08:16:00,2020-01-03 08:35:00,2020-01-03 08:37:00,577,1,21,21
73,2020-01-02,AGC,T-12138,2657986,2020-01-03 08:30:00,2020-01-03 08:35:00,2020-01-03 08:50:00,2020-01-03 08:56:00,581,1,20,21
74,2020-01-02,DHO,T-12138,2659095,2020-01-03 09:25:00,2020-01-03 09:27:00,2020-01-03 09:33:00,2020-01-03 09:37:00,634,1,8,10
75,2020-01-02,MRA,T-12138,2659193,2020-01-03 09:53:00,2020-01-03 09:55:00,2020-01-03 09:57:00,2020-01-03 10:09:00,661,1,4,14
76,2020-01-02,GWL,T-12138,2658454,2020-01-03 10:35:00,2020-01-03 10:40:00,2020-01-03 10:41:00,2020-01-03 10:46:00,699,1,6,6
77,2020-01-02,DBA,T-12138,2658414,2020-01-03 11:15:00,2020-01-03 11:17:00,2020-01-03 11:26:00,2020-01-03 11:28:00,741,1,11,11
78,2020-01-02,DAA,T-12138,2658432,2020-01-03 11:38:00,2020-01-03 11:40:00,2020-01-03 11:55:00,2020-01-03 11:57:00,772,1,17,17
79,2020-01-02,JHS,T-12138,2659350,2020-01-03 12:25:00,2020-01-03 12:35:00,2020-01-03 12:20:00,2020-01-03 12:35:00,797,1,-5,0
80,2020-01-02,BAB,T-12138,2657894,2020-01-03 13:00:00,2020-01-03 13:02:00,2020-01-03 13:44:00,2020-01-03 13:46:00,822,1,44,44
81,2020-01-02,LAR,T-12138,2658398,2020-01-03 13:47:00,2020-01-03 13:49:00,2020-01-03 14:35:00,2020-01-03 14:37:00,887,1,48,48
82,2020-01-02,BINA,T-12138,2657929,2020-01-03 14:45:00,2020-01-03 14:50:00,2020-01-03 16:49:00,2020-01-03 16:55:00,950,1,124,125
83,2020-01-02,BAQ,T-12138,2657881,2020-01-03 15:23:00,2020-01-03 15:25:00,2020-01-03 17:33:00,2020-01-03 17:35:00,996,1,130,130
84,2020-01-02,BHS,T-12138,2658012,2020-01-03 15:52:00,2020-01-03 15:54:00,2020-01-03 18:04:00,2020-01-03 18:15:00,1035,1,132,141
85,2020-01-02,BPL,T-12138,2658194,2020-01-03 16:50:00,2020-01-03 16:55:00,2020-01-03 19:09:00,2020-01-03 19:20:00,1088,1,139,145
86,2020-01-02,HBJ,T-12138,2658440,2020-01-03 17:07:00,2020-01-03 17:09:00,2020-01-03 19:31:00,2020-01-03 19:34:00,1095,1,144,145
87,2020-01-02,HBD,T-12138,2658443,2020-01-03 18:13:00,2020-01-03 18:15:00,2020-01-03 20:38:00,2020-01-03 20:40:00,1162,1,145,145
88,2020-01-02,ET,T-12138,2658804,2020-01-03 18:40:00,2020-01-03 18:46:00,2020-01-03 21:11:00,2020-01-03 21:25:00,1180,1,151,159
89,2020-01-02,BPF,T-12138,2731917,2020-01-03 19:13:00,2020-01-03 19:15:00,2020-01-03 22:05:00,2020-01-03 22:08:00,1214,1,172,173
90,2020-01-02,HD,T-12138,2658940,2020-01-03 19:43:00,2020-01-03 19:45:00,2020-01-03 22:43:00,2020-01-03 22:45:00,1256,1,180,180
91,2020-01-02,KKN,T-12138,2731952,2020-01-03 20:10:00,2020-01-03 20:12:00,2020-01-03 23:11:00,2020-01-03 23:13:00,1288,1,181,181
92,2020-01-02,KNW,T-12138,2658041,2020-01-03 21:35:00,2020-01-03 21:40:00,2020-01-04 00:36:00,2020-01-04 00:40:00,1364,1,181,180
93,2020-01-02,BAU,T-12138,2657885,2020-01-03 22:28:00,2020-01-03 22:30:00,2020-01-04 01:29:00,2020-01-04 01:31:00,1433,1,181,181
94,2020-01-02,BSL,T-12138,2657664,2020-01-03 23:30:00,2020-01-03 23:35:00,2020-01-04 02:13:00,2020-01-04 02:25:00,1487,1,163,170
95,2020-01-02,JL,T-12138,2658959,2020-01-03 23:59:00,2020-01-04 00:01:00,2020-01-04 02:53:00,2020-01-04 02:56:00,1511,2,174,175
96,2020-01-02,IGP,T-12138,2658818,2020-01-04 04:25:00,2020-01-04 04:30:00,2020-01-04 07:07:00,2020-01-04 07:08:00,1795,2,162,158
97,2020-01-02,CSMT,T-12138,10448787,2020-01-04 07:45:00,NaT,2020-01-04 10:45:00,2020-01-04 00:00:00,1928,2,180,0
98,2020-01-03,FZR,T-12138,2657812,NaT,2020-01-03 21:40:00,2020-01-03 00:00:00,2020-01-03 21:40:00,0,0,0,0
99,2020-01-03,FDK,T-12138,2659393,2020-01-03 22:05:00,2020-01-03 22:07:00,2020-01-03 22:18:00,2020-01-03 22:18:00,32,0,13,11

In [18]:
#function for checking delay values
def check_delay_values(x):
    if type(x[1])==pd._libs.tslibs.nattype.NaTType:
        return 0
    else:
        return x[0]

data['previous_arrival_delay'] = data.groupby(['runDate','trainCode'])['ArrivalDelay'].shift(fill_value=0)
data['previous_departure_delay'] = data.groupby(['runDate','trainCode'])['DepartureDelay'].shift(fill_value=0)


data['previous_departure_delay'] = data[['previous_departure_delay','scheduledDeparture']].apply(lambda x: check_delay_values(x),axis=1)

data['arrival_delay_for_each_stop'] = data['ArrivalDelay']-data['previous_arrival_delay']
data['departure_delay_for_each_stop'] = data['DepartureDelay']-data['previous_departure_delay']

In [22]:
data.head()

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop
0,2020-01-01,FZR,T-12138,2657812,NaT,2020-01-01 21:40:00,2020-01-01 00:00:00,2020-01-01 21:40:00,0,0,0,0,0,0,0,0
1,2020-01-01,FDK,T-12138,2659393,2020-01-01 22:05:00,2020-01-01 22:07:00,2020-01-01 22:16:00,2020-01-01 22:18:00,32,0,11,11,0,0,11,11
2,2020-01-01,KKP,T-12138,2658108,2020-01-01 22:23:00,2020-01-01 22:25:00,2020-01-01 22:37:00,2020-01-01 22:38:00,45,0,14,13,11,11,3,2
3,2020-01-01,GJUT,T-12138,2734206,2020-01-01 22:38:00,2020-01-01 22:40:00,2020-01-01 22:56:00,2020-01-01 22:57:00,61,0,18,17,14,13,4,4
4,2020-01-01,GNA,T-12138,2742572,2020-01-01 22:54:00,2020-01-01 22:56:00,2020-01-01 23:14:00,2020-01-01 23:15:00,76,0,20,19,18,17,2,2

## Treating null values in scheduledArrival, scheduledDeparture and actualDeparture columns

In [24]:
def null_value_imputation(x):
    if type(x[0])==pd._libs.tslibs.nattype.NaTType:
        x[0] = x[1] + timedelta(days=x[2])
        return x[0]
    else:
        return x[0]

In [25]:
data['scheduledArrival'] = data[['scheduledArrival','runDate','dayCount']].apply(lambda x: null_value_imputation(x),axis=1)

data['scheduledDeparture'] = data[['scheduledDeparture','runDate','dayCount']].apply(lambda x: null_value_imputation(x),axis=1)

In [27]:
data.head()

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop
0,2020-01-01,FZR,T-12138,2657812,2020-01-01 00:00:00,2020-01-01 21:40:00,2020-01-01 00:00:00,2020-01-01 21:40:00,0,0,0,0,0,0,0,0
1,2020-01-01,FDK,T-12138,2659393,2020-01-01 22:05:00,2020-01-01 22:07:00,2020-01-01 22:16:00,2020-01-01 22:18:00,32,0,11,11,0,0,11,11
2,2020-01-01,KKP,T-12138,2658108,2020-01-01 22:23:00,2020-01-01 22:25:00,2020-01-01 22:37:00,2020-01-01 22:38:00,45,0,14,13,11,11,3,2
3,2020-01-01,GJUT,T-12138,2734206,2020-01-01 22:38:00,2020-01-01 22:40:00,2020-01-01 22:56:00,2020-01-01 22:57:00,61,0,18,17,14,13,4,4
4,2020-01-01,GNA,T-12138,2742572,2020-01-01 22:54:00,2020-01-01 22:56:00,2020-01-01 23:14:00,2020-01-01 23:15:00,76,0,20,19,18,17,2,2

In [28]:
# data['actualDeparture'] = data[['actualDeparture','actualArrival']].apply(lambda x: null_value_imputation(x),axis=1)

In [29]:
data.isnull().sum()

runDate                           0
stations                          0
trainCode                         0
trainStationId                    0
scheduledArrival                  0
scheduledDeparture                0
actualArrival                     0
actualDeparture                  86
distance                          0
dayCount                          0
ArrivalDelay                      0
DepartureDelay                    0
previous_arrival_delay            0
previous_departure_delay          0
arrival_delay_for_each_stop       0
departure_delay_for_each_stop     0
dtype: int64

In [30]:
data[data.actualDeparture.isnull()]

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop
2495,2020-01-01,BPQ,T-12139,2658211,2020-01-02 09:45:00,2020-01-02,2020-01-02 10:12:00,NaT,891,1,27,0,27,0,0,0
2541,2020-01-02,BPQ,T-12139,2658211,2020-01-03 09:45:00,2020-01-03,2020-01-03 09:46:00,NaT,891,1,1,0,1,0,0,0
2575,2020-01-04,BPQ,T-12139,2658211,2020-01-05 09:45:00,2020-01-05,2020-01-05 10:16:00,NaT,891,1,31,0,31,0,0,0
2621,2020-01-05,BPQ,T-12139,2658211,2020-01-06 09:45:00,2020-01-06,2020-01-06 09:53:00,NaT,891,1,8,0,8,0,0,0
2657,2020-01-06,BPQ,T-12139,2658211,2020-01-07 09:45:00,2020-01-07,2020-01-07 10:14:00,NaT,891,1,29,0,29,0,0,0
2703,2020-01-07,BPQ,T-12139,2658211,2020-01-08 09:45:00,2020-01-08,2020-01-08 09:58:00,NaT,891,1,13,0,13,0,0,0
2747,2020-01-10,BPQ,T-12139,2658211,2020-01-11 09:45:00,2020-01-11,2020-01-11 09:58:00,NaT,891,1,13,0,13,0,0,0
2792,2020-01-11,BPQ,T-12139,2658211,2020-01-12 09:45:00,2020-01-12,2020-01-12 10:04:00,NaT,891,1,19,0,19,0,0,0
2838,2020-01-12,BPQ,T-12139,2658211,2020-01-13 09:45:00,2020-01-13,2020-01-13 09:48:00,NaT,891,1,3,0,3,0,0,0
2883,2020-01-13,BPQ,T-12139,2658211,2020-01-14 09:45:00,2020-01-14,2020-01-14 09:51:00,NaT,891,1,6,0,6,0,0,0
2929,2020-01-14,BPQ,T-12139,2658211,2020-01-15 09:45:00,2020-01-15,2020-01-15 09:48:00,NaT,891,1,3,0,3,0,0,0
2974,2020-01-15,BPQ,T-12139,2658211,2020-01-16 09:45:00,2020-01-16,2020-01-16 09:57:00,NaT,891,1,12,0,12,0,0,0
3020,2020-01-16,BPQ,T-12139,2658211,2020-01-17 09:45:00,2020-01-17,2020-01-17 09:52:00,NaT,891,1,7,0,7,0,0,0
3056,2020-01-18,BPQ,T-12139,2658211,2020-01-19 09:45:00,2020-01-19,2020-01-19 10:12:00,NaT,891,1,27,0,27,0,0,0
3102,2020-01-20,BPQ,T-12139,2658211,2020-01-21 09:45:00,2020-01-21,2020-01-21 10:02:00,NaT,891,1,17,0,17,0,0,0
3148,2020-01-21,BPQ,T-12139,2658211,2020-01-22 09:45:00,2020-01-22,2020-01-22 10:06:00,NaT,891,1,21,0,21,0,0,0
3194,2020-01-22,BPQ,T-12139,2658211,2020-01-23 09:45:00,2020-01-23,2020-01-23 09:56:00,NaT,891,1,11,0,11,0,0,0
3233,2020-01-23,BPQ,T-12139,2658211,2020-01-24 09:45:00,2020-01-24,2020-01-24 09:44:00,NaT,891,1,-1,0,-1,0,0,0
3261,2020-01-24,BPQ,T-12139,2658211,2020-01-25 09:45:00,2020-01-25,2020-01-25 10:26:00,NaT,891,1,41,0,41,0,0,0
3307,2020-01-25,BPQ,T-12139,2658211,2020-01-26 09:45:00,2020-01-26,2020-01-26 09:50:00,NaT,891,1,5,0,5,0,0,0
3350,2020-01-26,BPQ,T-12139,2658211,2020-01-27 09:45:00,2020-01-27,2020-01-27 10:05:00,NaT,891,1,20,0,20,0,0,0
3388,2020-01-27,BPQ,T-12139,2658211,2020-01-28 09:45:00,2020-01-28,2020-01-28 10:14:00,NaT,891,1,29,0,29,0,0,0
3434,2020-01-28,BPQ,T-12139,2658211,2020-01-29 09:45:00,2020-01-29,2020-01-29 09:54:00,NaT,891,1,9,0,9,0,0,0
3480,2020-01-29,BPQ,T-12139,2658211,2020-01-30 09:45:00,2020-01-30,2020-01-30 09:52:00,NaT,891,1,7,0,7,0,0,0
3526,2020-01-30,BPQ,T-12139,2658211,2020-01-31 09:45:00,2020-01-31,2020-01-31 09:55:00,NaT,891,1,10,0,10,0,0,0
3572,2020-01-31,BPQ,T-12139,2658211,2020-02-01 09:45:00,2020-02-01,2020-02-01 09:56:00,NaT,891,1,11,0,11,0,0,0
3618,2020-02-01,BPQ,T-12139,2658211,2020-02-02 09:45:00,2020-02-02,2020-02-02 09:49:00,NaT,891,1,4,0,4,0,0,0
3664,2020-02-02,BPQ,T-12139,2658211,2020-02-03 09:45:00,2020-02-03,2020-02-03 09:58:00,NaT,891,1,13,0,13,0,0,0
3707,2020-02-03,BPQ,T-12139,2658211,2020-02-04 09:45:00,2020-02-04,2020-02-04 10:03:00,NaT,891,1,18,0,18,0,0,0
3751,2020-02-04,BPQ,T-12139,2658211,2020-02-05 09:45:00,2020-02-05,2020-02-05 10:03:00,NaT,891,1,18,0,18,0,0,0
3796,2020-02-05,BPQ,T-12139,2658211,2020-02-06 09:45:00,2020-02-06,2020-02-06 10:03:00,NaT,891,1,18,0,18,0,0,0
3842,2020-02-06,BPQ,T-12139,2658211,2020-02-07 09:45:00,2020-02-07,2020-02-07 09:48:00,NaT,891,1,3,0,3,0,0,0
3883,2020-02-07,BPQ,T-12139,2658211,2020-02-08 09:45:00,2020-02-08,2020-02-08 10:07:00,NaT,891,1,22,0,22,0,0,0
3929,2020-02-08,BPQ,T-12139,2658211,2020-02-09 09:45:00,2020-02-09,2020-02-09 09:54:00,NaT,891,1,9,0,9,0,0,0
3975,2020-02-09,BPQ,T-12139,2658211,2020-02-10 09:45:00,2020-02-10,2020-02-10 09:56:00,NaT,891,1,11,0,11,0,0,0
4020,2020-02-10,BPQ,T-12139,2658211,2020-02-11 09:45:00,2020-02-11,2020-02-11 10:02:00,NaT,891,1,17,0,17,0,0,0
4066,2020-02-11,BPQ,T-12139,2658211,2020-02-12 09:45:00,2020-02-12,2020-02-12 10:03:00,NaT,891,1,18,0,18,0,0,0
4108,2020-02-12,BPQ,T-12139,2658211,2020-02-13 09:45:00,2020-02-13,2020-02-13 10:09:00,NaT,891,1,24,0,24,0,0,0
4154,2020-02-13,BPQ,T-12139,2658211,2020-02-14 09:45:00,2020-02-14,2020-02-14 09:51:00,NaT,891,1,6,0,6,0,0,0
4200,2020-02-14,BPQ,T-12139,2658211,2020-02-15 09:45:00,2020-02-15,2020-02-15 09:54:00,NaT,891,1,9,0,9,0,0,0
4246,2020-02-15,BPQ,T-12139,2658211,2020-02-16 09:45:00,2020-02-16,2020-02-16 09:58:00,NaT,891,1,13,0,13,0,0,0
4292,2020-02-16,BPQ,T-12139,2658211,2020-02-17 09:45:00,2020-02-17,2020-02-17 09:53:00,NaT,891,1,8,0,8,0,0,0
4337,2020-02-18,BPQ,T-12139,2658211,2020-02-19 09:45:00,2020-02-19,2020-02-19 09:58:00,NaT,891,1,13,0,13,0,0,0
4383,2020-02-19,BPQ,T-12139,2658211,2020-02-20 09:45:00,2020-02-20,2020-02-20 10:00:00,NaT,891,1,15,0,15,0,0,0
14431,2020-01-22,NDLS,T-12625,2657756,2020-01-24 13:45:00,2020-01-24,2020-01-24 14:13:00,NaT,3031,2,28,0,28,0,0,0
14514,2020-01-24,NDLS,T-12625,2657756,2020-01-26 13:45:00,2020-01-26,2020-01-26 14:00:00,NaT,3031,2,15,0,15,0,0,0
14555,2020-01-25,NDLS,T-12625,2657756,2020-01-27 13:45:00,2020-01-27,2020-01-27 13:54:00,NaT,3031,2,9,0,9,0,0,0
14598,2020-01-26,NDLS,T-12625,2657756,2020-01-28 13:45:00,2020-01-28,2020-01-28 13:36:00,NaT,3031,2,-9,0,-9,0,0,0
14640,2020-01-27,NDLS,T-12625,2657756,2020-01-29 13:45:00,2020-01-29,2020-01-29 13:57:00,NaT,3031,2,12,0,12,0,0,0
27902,2020-01-01,KLK,T-12925,2658088,2020-01-02 16:45:00,2020-01-02,2020-01-02 17:40:00,NaT,1676,1,55,55,55,0,0,55
27946,2020-01-02,KLK,T-12925,2658088,2020-01-03 16:45:00,2020-01-03,2020-01-03 17:08:00,NaT,1676,1,23,23,23,0,0,23
27990,2020-01-03,KLK,T-12925,2658088,2020-01-04 16:45:00,2020-01-04,2020-01-04 17:37:00,NaT,1676,1,52,52,52,0,0,52
28027,2020-01-04,KLK,T-12925,2658088,2020-01-05 16:45:00,2020-01-05,2020-01-05 17:53:00,NaT,1676,1,68,68,68,0,0,68
28069,2020-01-05,KLK,T-12925,2658088,2020-01-06 16:45:00,2020-01-06,2020-01-06 17:14:00,NaT,1676,1,29,29,29,0,0,29
28113,2020-01-06,KLK,T-12925,2658088,2020-01-07 16:45:00,2020-01-07,2020-01-07 16:54:00,NaT,1676,1,9,9,9,0,0,9
28156,2020-01-08,KLK,T-12925,2658088,2020-01-09 16:45:00,2020-01-09,2020-01-09 16:50:00,NaT,1676,1,5,4,5,0,0,4
28227,2020-01-10,KLK,T-12925,2658088,2020-01-11 16:45:00,2020-01-11,2020-01-11 16:54:00,NaT,1676,1,9,9,9,0,0,9
28271,2020-01-11,KLK,T-12925,2658088,2020-01-12 16:45:00,2020-01-12,2020-01-12 16:56:00,NaT,1676,1,11,11,11,0,0,11
28314,2020-01-12,KLK,T-12925,2658088,2020-01-13 16:45:00,2020-01-13,2020-01-13 16:57:00,NaT,1676,1,12,12,12,0,0,12
28355,2020-01-13,KLK,T-12925,2658088,2020-01-14 16:45:00,2020-01-14,2020-01-14 18:04:00,NaT,1676,1,79,79,79,0,0,79
28399,2020-01-14,KLK,T-12925,2658088,2020-01-15 16:45:00,2020-01-15,2020-01-15 17:12:00,NaT,1676,1,27,28,27,0,0,28
28442,2020-01-15,KLK,T-12925,2658088,2020-01-16 16:45:00,2020-01-16,2020-01-16 17:21:00,NaT,1676,1,36,36,36,0,0,36
28486,2020-01-17,KLK,T-12925,2658088,2020-01-18 16:45:00,2020-01-18,2020-01-18 17:47:00,NaT,1676,1,62,62,62,0,0,62
28529,2020-01-18,KLK,T-12925,2658088,2020-01-19 16:45:00,2020-01-19,2020-01-19 17:51:00,NaT,1676,1,66,66,66,0,0,66
28565,2020-01-20,KLK,T-12925,2658088,2020-01-21 16:45:00,2020-01-21,2020-01-21 18:04:00,NaT,1676,1,79,78,79,0,0,78
28671,2020-01-23,KLK,T-12925,2658088,2020-01-24 16:45:00,2020-01-24,2020-01-24 17:05:00,NaT,1676,1,20,20,20,0,0,20
28715,2020-01-24,KLK,T-12925,2658088,2020-01-25 16:45:00,2020-01-25,2020-01-25 16:56:00,NaT,1676,1,11,11,11,0,0,11
28758,2020-01-26,KLK,T-12925,2658088,2020-01-27 16:45:00,2020-01-27,2020-01-27 17:24:00,NaT,1676,1,39,38,39,0,0,38
28802,2020-01-27,KLK,T-12925,2658088,2020-01-28 16:45:00,2020-01-28,2020-01-28 16:50:00,NaT,1676,1,5,6,5,0,0,6
28845,2020-01-29,KLK,T-12925,2658088,2020-01-30 16:45:00,2020-01-30,2020-01-30 17:24:00,NaT,1676,1,39,40,39,0,0,40
28889,2020-01-30,KLK,T-12925,2658088,2020-01-31 16:45:00,2020-01-31,2020-01-31 17:14:00,NaT,1676,1,29,29,29,0,0,29
28933,2020-01-31,KLK,T-12925,2658088,2020-02-01 16:45:00,2020-02-01,2020-02-01 17:08:00,NaT,1676,1,23,22,23,0,0,22
28977,2020-02-02,KLK,T-12925,2658088,2020-02-03 16:45:00,2020-02-03,2020-02-03 17:15:00,NaT,1676,1,30,30,30,0,0,30
29020,2020-02-03,KLK,T-12925,2658088,2020-02-04 16:45:00,2020-02-04,2020-02-04 16:59:00,NaT,1676,1,14,14,14,0,0,14
29063,2020-02-04,KLK,T-12925,2658088,2020-02-05 16:45:00,2020-02-05,2020-02-05 17:10:00,NaT,1676,1,25,25,25,0,0,25
29142,2020-02-06,KLK,T-12925,2658088,2020-02-07 16:45:00,2020-02-07,2020-02-07 16:59:00,NaT,1676,1,14,14,14,0,0,14
29186,2020-02-08,KLK,T-12925,2658088,2020-02-09 16:45:00,2020-02-09,2020-02-09 17:06:00,NaT,1676,1,21,22,21,0,0,22
29229,2020-02-09,KLK,T-12925,2658088,2020-02-10 16:45:00,2020-02-10,2020-02-10 16:56:00,NaT,1676,1,11,11,11,0,0,11
29271,2020-02-10,KLK,T-12925,2658088,2020-02-11 16:45:00,2020-02-11,2020-02-11 17:08:00,NaT,1676,1,23,23,23,0,0,23
29314,2020-02-11,KLK,T-12925,2658088,2020-02-12 16:45:00,2020-02-12,2020-02-12 17:04:00,NaT,1676,1,19,19,19,0,0,19
29357,2020-02-12,KLK,T-12925,2658088,2020-02-13 16:45:00,2020-02-13,2020-02-13 18:05:00,NaT,1676,1,80,80,80,0,0,80
29400,2020-02-13,KLK,T-12925,2658088,2020-02-14 16:45:00,2020-02-14,2020-02-14 17:03:00,NaT,1676,1,18,18,18,0,0,18
29444,2020-02-14,KLK,T-12925,2658088,2020-02-15 16:45:00,2020-02-15,2020-02-15 16:56:00,NaT,1676,1,11,11,11,0,0,11
29487,2020-02-16,KLK,T-12925,2658088,2020-02-17 16:45:00,2020-02-17,2020-02-17 17:44:00,NaT,1676,1,59,59,59,0,0,59
29531,2020-02-18,KLK,T-12925,2658088,2020-02-19 16:45:00,2020-02-19,2020-02-19 17:22:00,NaT,1676,1,37,38,37,0,0,38
29574,2020-02-19,KLK,T-12925,2658088,2020-02-20 16:45:00,2020-02-20,2020-02-20 18:06:00,NaT,1676,1,81,81,81,0,0,81

In [31]:
data['actualDeparture'] = data[['actualDeparture','runDate','dayCount']].apply(lambda x: null_value_imputation(x),axis=1)

In [32]:
data[data.actualDeparture.isnull()]

Empty DataFrame
Columns: [runDate, stations, trainCode, trainStationId, scheduledArrival, scheduledDeparture, actualArrival, actualDeparture, distance, dayCount, ArrivalDelay, DepartureDelay, previous_arrival_delay, previous_departure_delay, arrival_delay_for_each_stop, departure_delay_for_each_stop]
Index: []

In [33]:
data.dropna(inplace=True)
data.reset_index(inplace=True,drop=True)

In [34]:
data.runDate.min()

Timestamp('2020-01-01 00:00:00')

In [35]:
data.runDate.max()

Timestamp('2020-02-19 00:00:00')

In [36]:
data['scheduledArrival_delta'] =  (data['scheduledArrival']-data['runDate']).apply(lambda x: x.total_seconds() / 60)
data['scheduledDeparture_delta'] =  (data['scheduledDeparture']-data['runDate']).apply(lambda x: x.total_seconds() / 60)
data['actualArrival_delta'] =  (data['actualArrival']-data['runDate']).apply(lambda x: x.total_seconds() / 60)
data['actualDeparture_delta'] =  (data['actualDeparture']-data['runDate']).apply(lambda x: x.total_seconds() / 60)

In [37]:
# data['Stoppage_time'] = (data['scheduledDeparture']-data['scheduledArrival']).apply(lambda x: x.total_seconds() / 60)

In [38]:
data

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop,scheduledArrival_delta,scheduledDeparture_delta,actualArrival_delta,actualDeparture_delta
0,2020-01-01,FZR,T-12138,2657812,2020-01-01 00:00:00,2020-01-01 21:40:00,2020-01-01 00:00:00,2020-01-01 21:40:00,0,0,0,0,0,0,0,0,0.0,1300.0,0.0,1300.0
1,2020-01-01,FDK,T-12138,2659393,2020-01-01 22:05:00,2020-01-01 22:07:00,2020-01-01 22:16:00,2020-01-01 22:18:00,32,0,11,11,0,0,11,11,1325.0,1327.0,1336.0,1338.0
2,2020-01-01,KKP,T-12138,2658108,2020-01-01 22:23:00,2020-01-01 22:25:00,2020-01-01 22:37:00,2020-01-01 22:38:00,45,0,14,13,11,11,3,2,1343.0,1345.0,1357.0,1358.0
3,2020-01-01,GJUT,T-12138,2734206,2020-01-01 22:38:00,2020-01-01 22:40:00,2020-01-01 22:56:00,2020-01-01 22:57:00,61,0,18,17,14,13,4,4,1358.0,1360.0,1376.0,1377.0
4,2020-01-01,GNA,T-12138,2742572,2020-01-01 22:54:00,2020-01-01 22:56:00,2020-01-01 23:14:00,2020-01-01 23:15:00,76,0,20,19,18,17,2,2,1374.0,1376.0,1394.0,1395.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29573,2020-02-19,KNN,T-12925,2658036,2020-02-20 15:56:00,2020-02-20 15:58:00,2020-02-20 17:17:00,2020-02-20 17:19:00,1644,1,81,81,18,70,63,11,2396.0,2398.0,2477.0,2479.0
29574,2020-02-19,KLK,T-12925,2658088,2020-02-20 16:45:00,2020-02-20 00:00:00,2020-02-20 18:06:00,2020-02-20 00:00:00,1676,1,81,81,81,0,0,81,2445.0,1440.0,2526.0,1440.0
29575,2020-02-19,LDH,T-12925,2658435,2020-02-20 16:46:00,2020-02-20 16:51:00,2020-02-20 17:55:00,2020-02-20 18:04:00,1687,1,69,73,81,81,-12,-8,2446.0,2451.0,2515.0,2524.0
29576,2020-02-19,PGW,T-12925,2658284,2020-02-20 17:19:00,2020-02-20 17:21:00,2020-02-20 18:39:00,2020-02-20 18:41:00,1723,1,80,80,69,73,11,7,2479.0,2481.0,2559.0,2561.0
29577,2020-02-19,ASR,T-12925,2657719,2020-02-20 19:20:00,2020-02-20 00:00:00,2020-02-20 20:27:00,2020-02-20 00:00:00,1823,1,67,0,80,0,-13,0,2600.0,1440.0,2667.0,1440.0

In [39]:
data.columns

Index(['runDate', 'stations', 'trainCode', 'trainStationId',
       'scheduledArrival', 'scheduledDeparture', 'actualArrival',
       'actualDeparture', 'distance', 'dayCount', 'ArrivalDelay',
       'DepartureDelay', 'previous_arrival_delay', 'previous_departure_delay',
       'arrival_delay_for_each_stop', 'departure_delay_for_each_stop',
       'scheduledArrival_delta', 'scheduledDeparture_delta',
       'actualArrival_delta', 'actualDeparture_delta'],
      dtype='object')

In [40]:
data2 = data.copy()

In [41]:
data2.sort_values(ascending=[True,True,True],by=['runDate','trainCode','distance'],inplace=True)

In [42]:
station_dummies = pd.get_dummies(data2.stations)
station_dummies

,ADH,ADI,AGC,AGN,AJJ,AJNI,AK,AKP,AKT,AKV,ALJN,AMLA,AN,ANND,ANV,ARA,ASN,ASR,AUBR,AWY,BAB,BALU,BAM,BAQ,BAU,BBS,BBU,BD,BDJ,BDL,BDTS,BDWD,BEAS,BG,BGZ,BH,BHC,BHS,BINA,BIY,BL,BLS,BLZ,BMB,BNC,BPA,BPF,BPH,BPHB,BPK,...,SNI,SNK,SNN,SNP,SPE,SPT,SRC,SRID,SRJ,SRR,SSB,SSM,ST,STA,SWM,SZM,TAE,TATA,TCR,TDD,TDL,TEL,THVM,TIR,TLD,TLY,TMR,TNA,TPTY,TRO,TRVL,TUN,TUNI,TUP,TVC,UBC,UD,UDN,UMB,VAK,VAPI,VARD,VNA,VSKP,VYA,VZM,WL,WR,WRR,ZN
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29573,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29574,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29575,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29576,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29577,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [43]:
trainCode_dummies = pd.get_dummies(data2.trainCode)
trainCode_dummies

,T-12138,T-12139,T-12295,T-12311,T-12321,T-12616,T-12617,T-12625,T-12656,T-12722,T-12809,T-12833,T-12834,T-12840,T-12925
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29573,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29574,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29575,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29576,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29577,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [44]:
data2 = pd.concat([data2,station_dummies,trainCode_dummies],axis=1)
data2

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop,scheduledArrival_delta,scheduledDeparture_delta,actualArrival_delta,actualDeparture_delta,ADH,ADI,AGC,AGN,AJJ,AJNI,AK,AKP,AKT,AKV,ALJN,AMLA,AN,ANND,ANV,ARA,ASN,ASR,AUBR,AWY,BAB,BALU,BAM,BAQ,BAU,BBS,BBU,BD,BDJ,BDL,...,SZM,TAE,TATA,TCR,TDD,TDL,TEL,THVM,TIR,TLD,TLY,TMR,TNA,TPTY,TRO,TRVL,TUN,TUNI,TUP,TVC,UBC,UD,UDN,UMB,VAK,VAPI,VARD,VNA,VSKP,VYA,VZM,WL,WR,WRR,ZN,T-12138,T-12139,T-12295,T-12311,T-12321,T-12616,T-12617,T-12625,T-12656,T-12722,T-12809,T-12833,T-12834,T-12840,T-12925
0,2020-01-01,FZR,T-12138,2657812,2020-01-01 00:00:00,2020-01-01 21:40:00,2020-01-01 00:00:00,2020-01-01 21:40:00,0,0,0,0,0,0,0,0,0.0,1300.0,0.0,1300.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2020-01-01,FDK,T-12138,2659393,2020-01-01 22:05:00,2020-01-01 22:07:00,2020-01-01 22:16:00,2020-01-01 22:18:00,32,0,11,11,0,0,11,11,1325.0,1327.0,1336.0,1338.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2020-01-01,KKP,T-12138,2658108,2020-01-01 22:23:00,2020-01-01 22:25:00,2020-01-01 22:37:00,2020-01-01 22:38:00,45,0,14,13,11,11,3,2,1343.0,1345.0,1357.0,1358.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2020-01-01,GJUT,T-12138,2734206,2020-01-01 22:38:00,2020-01-01 22:40:00,2020-01-01 22:56:00,2020-01-01 22:57:00,61,0,18,17,14,13,4,4,1358.0,1360.0,1376.0,1377.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2020-01-01,GNA,T-12138,2742572,2020-01-01 22:54:00,2020-01-01 22:56:00,2020-01-01 23:14:00,2020-01-01 23:15:00,76,0,20,19,18,17,2,2,1374.0,1376.0,1394.0,1395.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29573,2020-02-19,KNN,T-12925,2658036,2020-02-20 15:56:00,2020-02-20 15:58:00,2020-02-20 17:17:00,2020-02-20 17:19:00,1644,1,81,81,18,70,63,11,2396.0,2398.0,2477.0,2479.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29574,2020-02-19,KLK,T-12925,2658088,2020-02-20 16:45:00,2020-02-20 00:00:00,2020-02-20 18:06:00,2020-02-20 00:00:00,1676,1,81,81,81,0,0,81,2445.0,1440.0,2526.0,1440.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29575,2020-02-19,LDH,T-12925,2658435,2020-02-20 16:46:00,2020-02-20 16:51:00,2020-02-20 17:55:00,2020-02-20 18:04:00,1687,1,69,73,81,81,-12,-8,2446.0,2451.0,2515.0,2524.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29576,2020-02-19,PGW,T-12925,2658284,2020-02-20 17:19:00,2020-02-20 17:21:00,2020-02-20 18:39:00,2020-02-20 18:41:00,1723,1,80,80,69,73,11,7,2479.0,2481.0,2559.0,2561.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29577,2020-02-19,ASR,T-12925,2657719,2020-02-20 19:20:00,2020-02-20 00:00:00,2020-02-20 20:27:00,2020-02-20 00:00:00,1823,1,67,0,80,0,-13,0,2600.0,1440.0,2667.0,1440.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [45]:
#not going to use standard train_test_split beacause i want to split data frame based on run date
train_size = int(len(data2) * 0.75)
test_size = len(data2) - train_size
train, test = data2.iloc[0:train_size], data2.iloc[train_size:len(data2)]
print(train.shape, test.shape)

(22183, 384) (7395, 384)

In [46]:
# train_run_time_df = data2.groupby(['trainCode','runDate']).agg({'scheduledDeparture':'min','scheduledArrival':'max'})
# train_run_time_df['train_run_time'] =  (train_run_time_df['scheduledArrival'] - train_run_time_df['scheduledDeparture']).apply(lambda x: x.total_seconds() / 60)
# train_run_time_df.reset_index(inplace=True)
# train_run_time_df

In [47]:
# train_run_time_df.train_run_time.unique()

In [48]:
data2.dayCount.value_counts()

1    17950
0     7815
2     3813
Name: dayCount, dtype: int64

In [49]:
# train_wise_avg_delay = train.groupby(['trainCode','stations']).agg({'arrival_delay_for_each_stop':'mean','departure_delay_for_each_stop':'mean'})
# train_wise_avg_delay.columns=['train_wise_avg_arrival_delay', 'train_wise_avg_departure_delay']
# train_wise_avg_delay.reset_index(inplace=True)
# train_wise_avg_delay

In [50]:
# station_wise_avg_delay = train.groupby(['stations']).agg({'ArrivalDelay':'mean','DepartureDelay':'mean'})
# station_wise_avg_delay.columns=['station_wise_avg_arrival_delay', 'station_wise_avg_departure_delay']
# station_wise_avg_delay.reset_index(inplace=True)
# station_wise_avg_delay

In [51]:
# train = pd.merge(train,train_run_time_df[['trainCode','runDate','train_run_time']],on=['trainCode','runDate'],how='left')
# train = pd.merge(train,train_wise_avg_delay,on=['trainCode','stations'],how='left')
# # train = pd.merge(train,station_wise_avg_delay,on=['stations'],how='left')

In [52]:
# test = pd.merge(test,train_run_time_df[['trainCode','runDate','train_run_time']],on=['trainCode','runDate'],how='left')
# test = pd.merge(test,train_wise_avg_delay,on=['trainCode','stations'],how='left')
# # test = pd.merge(test,station_wise_avg_delay,on=['stations'],how='left')

In [53]:
train.drop(columns=['trainStationId','scheduledArrival','scheduledDeparture','actualArrival','actualDeparture'],inplace=True)
train

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,runDate,stations,trainCode,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop,scheduledArrival_delta,scheduledDeparture_delta,actualArrival_delta,actualDeparture_delta,ADH,ADI,AGC,AGN,AJJ,AJNI,AK,AKP,AKT,AKV,ALJN,AMLA,AN,ANND,ANV,ARA,ASN,ASR,AUBR,AWY,BAB,BALU,BAM,BAQ,BAU,BBS,BBU,BD,BDJ,BDL,BDTS,BDWD,BEAS,BG,BGZ,...,SZM,TAE,TATA,TCR,TDD,TDL,TEL,THVM,TIR,TLD,TLY,TMR,TNA,TPTY,TRO,TRVL,TUN,TUNI,TUP,TVC,UBC,UD,UDN,UMB,VAK,VAPI,VARD,VNA,VSKP,VYA,VZM,WL,WR,WRR,ZN,T-12138,T-12139,T-12295,T-12311,T-12321,T-12616,T-12617,T-12625,T-12656,T-12722,T-12809,T-12833,T-12834,T-12840,T-12925
0,2020-01-01,FZR,T-12138,0,0,0,0,0,0,0,0,0.0,1300.0,0.0,1300.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2020-01-01,FDK,T-12138,32,0,11,11,0,0,11,11,1325.0,1327.0,1336.0,1338.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2020-01-01,KKP,T-12138,45,0,14,13,11,11,3,2,1343.0,1345.0,1357.0,1358.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2020-01-01,GJUT,T-12138,61,0,18,17,14,13,4,4,1358.0,1360.0,1376.0,1377.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2020-01-01,GNA,T-12138,76,0,20,19,18,17,2,2,1374.0,1376.0,1394.0,1395.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871,2020-02-07,IGP,T-12138,1795,2,-10,0,37,37,-47,-37,3145.0,3150.0,3135.0,3150.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1872,2020-02-07,KYN,T-12138,1877,2,-1,0,-10,0,9,0,3260.0,3265.0,3259.0,3265.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1873,2020-02-07,DR,T-12138,1919,2,0,0,-1,0,1,0,3302.0,3305.0,3302.0,3305.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1874,2020-02-07,CSMT,T-12138,1928,2,2,0,0,0,2,0,3345.0,2880.0,3347.0,2880.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3843,2020-02-07,CSMT,T-12139,0,0,0,2,0,0,0,2,0.0,895.0,0.0,897.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [54]:
test.drop(columns=['trainStationId','scheduledArrival','scheduledDeparture','actualArrival','actualDeparture'],inplace=True)
test

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,runDate,stations,trainCode,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop,scheduledArrival_delta,scheduledDeparture_delta,actualArrival_delta,actualDeparture_delta,ADH,ADI,AGC,AGN,AJJ,AJNI,AK,AKP,AKT,AKV,ALJN,AMLA,AN,ANND,ANV,ARA,ASN,ASR,AUBR,AWY,BAB,BALU,BAM,BAQ,BAU,BBS,BBU,BD,BDJ,BDL,BDTS,BDWD,BEAS,BG,BGZ,...,SZM,TAE,TATA,TCR,TDD,TDL,TEL,THVM,TIR,TLD,TLY,TMR,TNA,TPTY,TRO,TRVL,TUN,TUNI,TUP,TVC,UBC,UD,UDN,UMB,VAK,VAPI,VARD,VNA,VSKP,VYA,VZM,WL,WR,WRR,ZN,T-12138,T-12139,T-12295,T-12311,T-12321,T-12616,T-12617,T-12625,T-12656,T-12722,T-12809,T-12833,T-12834,T-12840,T-12925
3844,2020-02-07,DR,T-12139,9,0,10,8,0,2,10,6,902.0,905.0,912.0,913.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3845,2020-02-07,TNA,T-12139,33,0,5,3,10,8,-5,-5,930.0,933.0,935.0,936.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3846,2020-02-07,KYN,T-12139,51,0,5,6,5,3,0,3,955.0,958.0,960.0,964.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3847,2020-02-07,KSRA,T-12139,118,0,13,18,5,6,8,12,1018.0,1020.0,1031.0,1038.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3848,2020-02-07,IGP,T-12139,133,0,10,10,13,18,-3,-8,1050.0,1055.0,1060.0,1065.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29573,2020-02-19,KNN,T-12925,1644,1,81,81,18,70,63,11,2396.0,2398.0,2477.0,2479.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29574,2020-02-19,KLK,T-12925,1676,1,81,81,81,0,0,81,2445.0,1440.0,2526.0,1440.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29575,2020-02-19,LDH,T-12925,1687,1,69,73,81,81,-12,-8,2446.0,2451.0,2515.0,2524.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29576,2020-02-19,PGW,T-12925,1723,1,80,80,69,73,11,7,2479.0,2481.0,2559.0,2561.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29577,2020-02-19,ASR,T-12925,1823,1,67,0,80,0,-13,0,2600.0,1440.0,2667.0,1440.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [55]:
data.corr()

,trainStationId,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop,scheduledArrival_delta,scheduledDeparture_delta,actualArrival_delta,actualDeparture_delta
trainStationId,1.000000,0.038990,0.057406,-0.017985,-0.035323,0.001342,-0.018252,-0.054018,-0.052291,0.017071,0.035775,0.015268,0.032876
distance,0.038990,1.000000,0.751798,0.188552,0.173111,0.219314,0.202379,-0.079269,-0.081956,0.849089,0.832069,0.844947,0.827828
dayCount,0.057406,0.751798,1.000000,0.197455,0.177490,0.222191,0.202278,-0.062325,-0.068394,0.874891,0.871323,0.869169,0.865172
ArrivalDelay,-0.017985,0.188552,0.197455,1.000000,0.973736,0.935442,0.927497,0.209480,0.170560,0.278281,0.278406,0.326224,0.327340
DepartureDelay,-0.035323,0.173111,0.177490,0.973736,1.000000,0.915732,0.944925,0.190537,0.197888,0.258979,0.269422,0.306124,0.319928
previous_arrival_delay,0.001342,0.219314,0.222191,0.935442,0.915732,1.000000,0.970504,-0.149682,-0.133880,0.305322,0.305483,0.349561,0.351161
previous_departure_delay,-0.018252,0.202379,0.202278,0.927497,0.944925,0.970504,1.000000,-0.090312,-0.133825,0.287767,0.299156,0.331888,0.346614
arrival_delay_for_each_stop,-0.054018,-0.079269,-0.062325,0.209480,0.190537,-0.149682,-0.090312,1.000000,0.847423,-0.066205,-0.066300,-0.054478,-0.055780
departure_delay_for_each_stop,-0.052291,-0.081956,-0.068394,0.170560,0.197888,-0.133880,-0.133825,0.847423,1.000000,-0.077689,-0.080179,-0.067078,-0.069388
scheduledArrival_delta,0.017071,0.849089,0.874891,0.278281,0.258979,0.305322,0.287767,-0.066205,-0.077689,1.000000,0.972307,0.997984,0.970285
scheduledDeparture_delta,0.035775,0.832069,0.871323,0.278406,0.269422,0.305483,0.299156,-0.066300,-0.080179,0.972307,1.000000,0.970294,0.997994
actualArrival_delta,0.015268,0.844947,0.869169,0.326224,0.306124,0.349561,0.331888,-0.054478,-0.067078,0.997984,0.970294,1.000000,0.971967
actualDeparture_delta,0.032876,0.827828,0.865172,0.327340,0.319928,0.351161,0.346614,-0.055780,-0.069388,0.970285,0.997994,0.971967,1.000000

# Arrival Model

In [144]:
data3 = data.copy()

In [145]:
data3.head()

,runDate,stations,trainCode,trainStationId,scheduledArrival,scheduledDeparture,actualArrival,actualDeparture,distance,dayCount,ArrivalDelay,DepartureDelay,previous_arrival_delay,previous_departure_delay,arrival_delay_for_each_stop,departure_delay_for_each_stop,scheduledArrival_delta,scheduledDeparture_delta,actualArrival_delta,actualDeparture_delta
0,2020-01-01,FZR,T-12138,2657812,2020-01-01 00:00:00,2020-01-01 21:40:00,2020-01-01 00:00:00,2020-01-01 21:40:00,0,0,0,0,0,0,0,0,0.0,1300.0,0.0,1300.0
1,2020-01-01,FDK,T-12138,2659393,2020-01-01 22:05:00,2020-01-01 22:07:00,2020-01-01 22:16:00,2020-01-01 22:18:00,32,0,11,11,0,0,11,11,1325.0,1327.0,1336.0,1338.0
2,2020-01-01,KKP,T-12138,2658108,2020-01-01 22:23:00,2020-01-01 22:25:00,2020-01-01 22:37:00,2020-01-01 22:38:00,45,0,14,13,11,11,3,2,1343.0,1345.0,1357.0,1358.0
3,2020-01-01,GJUT,T-12138,2734206,2020-01-01 22:38:00,2020-01-01 22:40:00,2020-01-01 22:56:00,2020-01-01 22:57:00,61,0,18,17,14,13,4,4,1358.0,1360.0,1376.0,1377.0
4,2020-01-01,GNA,T-12138,2742572,2020-01-01 22:54:00,2020-01-01 22:56:00,2020-01-01 23:14:00,2020-01-01 23:15:00,76,0,20,19,18,17,2,2,1374.0,1376.0,1394.0,1395.0

In [146]:
data3['trainCode'].unique()

array(['T-12138', 'T-12139', 'T-12295', 'T-12311', 'T-12321', 'T-12616',
       'T-12617', 'T-12625', 'T-12656', 'T-12722', 'T-12809', 'T-12833',
       'T-12834', 'T-12840', 'T-12925'], dtype=object)

In [147]:
trainCode_encoding = {data3['trainCode'].unique()[i]: i+1 for i in range(len(data3['trainCode'].unique()))}
trainCode_encoding

{'T-12138': 1,
 'T-12139': 2,
 'T-12295': 3,
 'T-12311': 4,
 'T-12321': 5,
 'T-12616': 6,
 'T-12617': 7,
 'T-12625': 8,
 'T-12656': 9,
 'T-12722': 10,
 'T-12809': 11,
 'T-12833': 12,
 'T-12834': 13,
 'T-12840': 14,
 'T-12925': 15}

In [148]:
stations_encoding = {data3['stations'].unique()[i]: i+1 for i in range(len(data3['stations'].unique()))}
stations_encoding

{'FZR': 1,
 'FDK': 2,
 'KKP': 3,
 'GJUT': 4,
 'GNA': 5,
 'BTI': 6,
 'MAUR': 7,
 'MSZ': 8,
 'BLZ': 9,
 'BRZ': 10,
 'JHL': 11,
 'TUN': 12,
 'NRW': 13,
 'JIND': 14,
 'ROK': 15,
 'BGZ': 16,
 'DKZ': 17,
 'NDLS': 18,
 'FDB': 19,
 'KSV': 20,
 'MTJ': 21,
 'RKM': 22,
 'AGC': 23,
 'DHO': 24,
 'MRA': 25,
 'GWL': 26,
 'DBA': 27,
 'DAA': 28,
 'JHS': 29,
 'BAB': 30,
 'LAR': 31,
 'BINA': 32,
 'BAQ': 33,
 'BHS': 34,
 'BPL': 35,
 'HBJ': 36,
 'HBD': 37,
 'ET': 38,
 'BPF': 39,
 'HD': 40,
 'KKN': 41,
 'KNW': 42,
 'BAU': 43,
 'BSL': 44,
 'JL': 45,
 'CSN': 46,
 'MMR': 47,
 'NK': 48,
 'DVL': 49,
 'IGP': 50,
 'SSB': 51,
 'CSMT': 52,
 'KYN': 53,
 'DR': 54,
 'TNA': 55,
 'KSRA': 56,
 'NR': 57,
 'LS': 58,
 'NGN': 59,
 'PC': 60,
 'SEG': 61,
 'AK': 62,
 'MZR': 63,
 'BD': 64,
 'CND': 65,
 'DMN': 66,
 'PLO': 67,
 'WR': 68,
 'SEGM': 69,
 'BPK': 70,
 'SNN': 71,
 'SNI': 72,
 'HGT': 73,
 'NGI': 74,
 'CKNI': 75,
 'AJNI': 76,
 'WRR': 77,
 'NGP': 78,
 'MJRI': 79,
 'BUX': 80,
 'TAE': 81,
 'CD': 82,
 'BUPH': 83,
 'GNVR': 84,
 'BPQ': 85,
 'VNA': 86,
 'BDWD': 87,
 'MKU': 88,
 'NN': 89,
 'JM': 90,
 'SBC': 91,
 'BNC': 92,
 'KJM': 93,
 'BWT': 94,
 'KPN': 95,
 'JTJ': 96,
 'KPD': 97,
 'AJJ': 98,
 'MAS': 99,
 'GDR': 100,
 'NLR': 101,
 'OGL': 102,
 'BZA': 103,
 'WL': 104,
 'RDM': 105,
 'SKZR': 106,
 'PAR': 107,
 'BZU': 108,
 'GDYA': 109,
 'PPI': 110,
 'NU': 111,
 'JBP': 112,
 'KTE': 113,
 'MYR': 114,
 'STA': 115,
 'PCOI': 116,
 'MZP': 117,
 'DDU': 118,
 'BXR': 119,
 'ARA': 120,
 'DNR': 121,
 'HWH': 122,
 'BWN': 123,
 'DGR': 124,
 'ASN': 125,
 'DHN': 126,
 'GMO': 127,
 'PNME': 128,
 'HZD': 129,
 'KQR': 130,
 'GAYA': 131,
 'DOS': 132,
 'SSM': 133,
 'BBU': 134,
 'PRYJ': 135,
 'FTP': 136,
 'CNB': 137,
 'PHD': 138,
 'ETW': 139,
 'SKB': 140,
 'FZD': 141,
 'TDL': 142,
 'HRS': 143,
 'ALJN': 144,
 'KRJ': 145,
 'GZB': 146,
 'DLI': 147,
 'SZM': 148,
 'SNP': 149,
 'GNU': 150,
 'SMK': 151,
 'PNP': 152,
 'KUN': 153,
 'KKDE': 154,
 'UMB': 155,
 'CDG': 156,
 'CNDM': 157,
 'KLK': 158,
 'PAN': 159,
 'RNG': 160,
 'BRR': 161,
 'AUBR': 162,
 'CAR': 163,
 'BDL': 164,
 'SRJ': 165,
 'MKP': 166,
 'SRID': 167,
 'KY': 168,
 'GAR': 169,
 'NPNR': 170,
 'AMLA': 171,
 'NRKR': 172,
 'BPA': 173,
 'MCI': 174,
 'KMT': 175,
 'TEL': 176,
 'BPP': 177,
 'CLX': 178,
 'ERS': 179,
 'AWY': 180,
 'TCR': 181,
 'SRR': 182,
 'PTB': 183,
 'KTU': 184,
 'TIR': 185,
 'PGI': 186,
 'FK': 187,
 'CLT': 188,
 'QLD': 189,
 'BDJ': 190,
 'TLY': 191,
 'CAN': 192,
 'PAZ': 193,
 'PAY': 194,
 'NLE': 195,
 'KZE': 196,
 'KGQ': 197,
 'MAJN': 198,
 'UD': 199,
 'KUDA': 200,
 'BTJL': 201,
 'KT': 202,
 'KAWR': 203,
 'MAO': 204,
 'THVM': 205,
 'KKW': 206,
 'RN': 207,
 'CHI': 208,
 'PNVL': 209,
 'NZM': 210,
 'TVC': 211,
 'VAK': 212,
 'QLN': 213,
 'KYJ': 214,
 'MVLK': 215,
 'CNGR': 216,
 'TRVL': 217,
 'CGY': 218,
 'KTYM': 219,
 'VARD': 220,
 'ERN': 221,
 'OTP': 222,
 'PGT': 223,
 'CBE': 224,
 'TUP': 225,
 'ED': 226,
 'SA': 227,
 'CTO': 228,
 'TPTY': 229,
 'RU': 230,
 'SPE': 231,
 'KVZ': 232,
 'MABD': 233,
 'DXG': 234,
 'AN': 235,
 'SNK': 236,
 'DDE': 237,
 'NDB': 238,
 'VYA': 239,
 'UDN': 240,
 'ST': 241,
 'AKV': 242,
 'BRC': 243,
 'ANND': 244,
 'ND': 245,
 'MAN': 246,
 'ADI': 247,
 'BVH': 248,
 'MABA': 249,
 'MTY': 250,
 'KATL': 251,
 'PDPL': 252,
 'JMKT': 253,
 'KZJ': 254,
 'ZN': 255,
 'BG': 256,
 'SC': 257,
 'HYB': 258,
 'BRD': 259,
 'TMR': 260,
 'G': 261,
 'DGG': 262,
 'RJN': 263,
 'DURG': 264,
 'R': 265,
 'BYT': 266,
 'BSP': 267,
 'CPH': 268,
 'SKT': 269,
 'KHS': 270,
 'RIG': 271,
 'BRJN': 272,
 'JSG': 273,
 'ROU': 274,
 'TATA': 275,
 'CKP': 276,
 'SRC': 277,
 'KGP': 278,
 'BH': 279,
 'BIY': 280,
 'MID': 281,
 'NWU': 282,
 'KP': 283,
 'TRO': 284,
 'AGN': 285,
 'BPHB': 286,
 'TLD': 287,
 'AKT': 288,
 'NIA': 289,
 'BUA': 290,
 'BPH': 291,
 'BMB': 292,
 'GP': 293,
 'MCA': 294,
 'PKU': 295,
 'EE': 296,
 'TDD': 297,
 'NDD': 298,
 'RJY': 299,
 'SLO': 300,
 'ANV': 301,
 'TUNI': 302,
 'AKP': 303,
 'VSKP': 304,
 'VZM': 305,
 'CPP': 306,
 'CHE': 307,
 'NWP': 308,
 'PSA': 309,
 'SPT': 310,
 'IPM': 311,
 'BAM': 312,
 'CAP': 313,
 'BALU': 314,
 'KUR': 315,
 'BBS': 316,
 'CTC': 317,
 'JJKR': 318,
 'BHC': 319,
 'BLS': 320,
 'BDTS': 321,
 'ADH': 322,
 'BVI': 323,
 'DRD': 324,
 'VAPI': 325,
 'BL': 326,
 'NVS': 327,
 'GDA': 328,
 'DHD': 329,
 'MGN': 330,
 'NAD': 331,
 'SGZ': 332,
 'RMA': 333,
 'KOTA': 334,
 'SWM': 335,
 'GGC': 336,
 'HAN': 337,
 'BXN': 338,
 'BTE': 339,
 'UBC': 340,
 'SIR': 341,
 'KNN': 342,
 'LDH': 343,
 'PGW': 344,
 'JRC': 345,
 'JUC': 346,
 'BEAS': 347,
 'ASR': 348,
 'RTM': 349}

In [149]:
data3["trainCode"] = data3["trainCode"].apply(lambda x: trainCode_encoding[x])
data3["trainCode"]

0         1
1         1
2         1
3         1
4         1
         ..
29573    15
29574    15
29575    15
29576    15
29577    15
Name: trainCode, Length: 29578, dtype: int64

In [150]:
data3["stations"] = data3["stations"].apply(lambda x: stations_encoding[x])
data3["stations"]

0          1
1          2
2          3
3          4
4          5
        ...
29573    342
29574    158
29575    343
29576    344
29577    348
Name: stations, Length: 29578, dtype: int64

In [151]:
data3.columns

Index(['runDate', 'stations', 'trainCode', 'trainStationId',
       'scheduledArrival', 'scheduledDeparture', 'actualArrival',
       'actualDeparture', 'distance', 'dayCount', 'ArrivalDelay',
       'DepartureDelay', 'previous_arrival_delay', 'previous_departure_delay',
       'arrival_delay_for_each_stop', 'departure_delay_for_each_stop',
       'scheduledArrival_delta', 'scheduledDeparture_delta',
       'actualArrival_delta', 'actualDeparture_delta'],
      dtype='object')

In [131]:
feature_cols = ['stations', 'trainCode', 'distance', 'dayCount','scheduledArrival_delta', 
                'scheduledDeparture_delta',
               ]

In [178]:
#not going to use standard train_test_split beacause i want to split data frame based on run date
train_size = int(len(data3) * 0.75)
test_size = len(data3) - train_size
train, test = data3.iloc[0:train_size], data3.iloc[train_size:len(data3)]
print(train.shape, test.shape)

(22183, 20) (7395, 20)

In [133]:
X_train, y_train = train[feature_cols], train['ArrivalDelay']

X_test, y_test = test[feature_cols], test['ArrivalDelay']

In [134]:


# Parameter Tuning
model = xgboost.XGBRegressor()
param_dist = {"max_depth": [5,10,15],
              "min_child_weight" : [1,3,6],
              "n_estimators": [100,200,300],
              "learning_rate": [0.05, 0.03,0.01],}

grid_search = GridSearchCV(model, param_grid=param_dist, cv = 3, 
                                   verbose=10, n_jobs=-1)

In [135]:
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 81 candidates, totalling 243 fits

[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    3.1s
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    9.4s
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:   12.2s
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   16.3s
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   21.4s
[Parallel(n_jobs=-1)]: Done  45 tasks      | elapsed:   31.4s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:   40.8s
[Parallel(n_jobs=-1)]: Done  69 tasks      | elapsed:   56.4s
[Parallel(n_jobs=-1)]: Done  82 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done  97 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 112 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 129 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 165 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 205 tasks      | elapsed:  2.8min
[Parallel(n_jobs=-1)]: Done 226 tasks      | elapsed:  3.3min
[Parallel(n_jobs=-1)]: Done 243 out of 243 | elapsed:  3.7min finished

GridSearchCV(cv=3, error_score='raise',
       estimator=XGBRegressor(base_score=None, booster=None, colsample_bylevel=None,
       colsample_bynode=None, colsample_bytree=None, gamma=None,
       gpu_id=None, importance_type='gain', interaction_constraints=None,
       learning_rate=None, max_delta_step=None, max_depth=None,
       min_child_we..._pos_weight=None, subsample=None,
       tree_method=None, validate_parameters=None, verbosity=None),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid={'max_depth': [5, 10, 15], 'min_child_weight': [1, 3, 6], 'n_estimators': [100, 200, 300], 'learning_rate': [0.05, 0.03, 0.01]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=10)

In [136]:
grid_search.best_estimator_

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints='',
       learning_rate=0.03, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=nan, monotone_constraints='()',
       n_estimators=100, n_jobs=8, num_parallel_tree=1,
       objective='reg:squarederror', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
       validate_parameters=1, verbosity=None)

In [137]:
arrival_xgb = xgboost.XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.7,
       colsample_bynode=0.7, colsample_bytree=0.7, gamma=0.25, gpu_id=-1,
       importance_type='gain', interaction_constraints='',
       learning_rate=0.03, max_delta_step=0, max_depth=6,
       min_child_weight=7, missing=np.nan, monotone_constraints='()',
       n_estimators=100, n_jobs=8, num_parallel_tree=1,
       objective='reg:squarederror', random_state=0, reg_alpha=0.8,
       reg_lambda=0.8, scale_pos_weight=1, subsample=0.5,
       tree_method='exact', validate_parameters=1, verbosity=None)

In [138]:
arrival_xgb.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.7,
       colsample_bynode=0.7, colsample_bytree=0.7, gamma=0.25, gpu_id=-1,
       importance_type='gain', interaction_constraints='',
       learning_rate=0.03, max_delta_step=0, max_depth=6,
       min_child_weight=7, missing=nan, monotone_constraints='()',
       n_estimators=100, n_jobs=8, num_parallel_tree=1,
       objective='reg:squarederror', random_state=0, reg_alpha=0.8,
       reg_lambda=0.8, scale_pos_weight=1, subsample=0.5,
       tree_method='exact', validate_parameters=1, verbosity=None)

In [140]:
from sklearn.metrics import mean_squared_error
import math
print(mean_squared_error(y_test, y_pred))
print(math.sqrt(mean_squared_error(y_test, y_pred)))

779.5200628050591
27.919886511321263

In [215]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.15751339903111516

# Departure Model

In [179]:
X_train, y_train = train[feature_cols], train['DepartureDelay']
X_test, y_test = test[feature_cols], test['DepartureDelay']

In [180]:
delay_xgb = xgboost.XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.7,
       colsample_bynode=0.7, colsample_bytree=0.7, gamma=0.25, gpu_id=-1,
       importance_type='gain', interaction_constraints='',
       learning_rate=0.03, max_delta_step=0, max_depth=6,
       min_child_weight=7, missing=np.nan, monotone_constraints='()',
       n_estimators=100, n_jobs=8, num_parallel_tree=1,
       objective='reg:squarederror', random_state=0, reg_alpha=0.5,
       reg_lambda=1, scale_pos_weight=1, subsample=0.5,
       tree_method='exact', validate_parameters=1, verbosity=None)

In [181]:
delay_xgb.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.7,
       colsample_bynode=0.7, colsample_bytree=0.7, gamma=0.25, gpu_id=-1,
       importance_type='gain', interaction_constraints='',
       learning_rate=0.03, max_delta_step=0, max_depth=6,
       min_child_weight=7, missing=nan, monotone_constraints='()',
       n_estimators=100, n_jobs=8, num_parallel_tree=1,
       objective='reg:squarederror', random_state=0, reg_alpha=0.5,
       reg_lambda=1, scale_pos_weight=1, subsample=0.5,
       tree_method='exact', validate_parameters=1, verbosity=None)

In [183]:
from sklearn.metrics import mean_squared_error
import math
print(mean_squared_error(y_test, y_pred))
print(math.sqrt(mean_squared_error(y_test, y_pred)))

757.8680895773095
27.529404090486768

In [184]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.15751339903111516

In [185]:
#Predicting on provided test dataset

In [193]:
test_df = pd.read_csv('test.csv')

In [194]:
test_df.head()

,runDate,stations,trainId,trainCode,index,trainStationId,scheduledArrival,scheduledDeparture,distance,dayCount,day
0,2020-02-20,FZR,11528,12138,1,2657812,NaN,2020-02-20 21:40:00,0,0,Thursday
1,2020-02-20,FDK,11528,12138,2,2659393,2020-02-20 22:05:00,2020-02-20 22:07:00,32,0,Thursday
2,2020-02-20,KKP,11528,12138,3,2658108,2020-02-20 22:23:00,2020-02-20 22:25:00,45,0,Thursday
3,2020-02-20,GJUT,11528,12138,4,2734206,2020-02-20 22:38:00,2020-02-20 22:40:00,61,0,Thursday
4,2020-02-20,GNA,11528,12138,5,2742572,2020-02-20 22:54:00,2020-02-20 22:56:00,76,0,Thursday

In [195]:
test_df.isna().sum()

runDate                0
stations               0
trainId                0
trainCode              0
index                  0
trainStationId         0
scheduledArrival      15
scheduledDeparture    17
distance               0
dayCount               0
day                    0
dtype: int64

In [196]:
test_df[(test_df.scheduledArrival.isnull())|(test_df.scheduledDeparture.isnull())]

,runDate,stations,trainId,trainCode,index,trainStationId,scheduledArrival,scheduledDeparture,distance,dayCount,day
0,2020-02-20,FZR,11528,12138,1,2657812,NaN,2020-02-20 21:40:00,0,0,Thursday
53,2020-02-20,CSMT,11528,12138,54,10448787,2020-02-22 07:45:00,NaN,1928,2,Thursday
54,2020-02-20,CSMT,11529,12139,1,10448787,NaN,2020-02-20 14:55:00,0,0,Thursday
92,2020-02-20,NGP,11529,12139,39,2659359,2020-02-21 06:05:00,NaN,833,1,Thursday
99,2020-02-20,BPQ,11529,12139,46,2658211,2020-02-21 09:45:00,NaN,891,1,Thursday
100,2020-02-20,SBC,11615,12295,1,2659471,NaN,2020-02-20 09:00:00,0,0,Thursday
135,2020-02-20,DNR,11615,12295,36,2659203,2020-02-22 09:05:00,NaN,2696,2,Thursday
136,2020-02-20,HWH,13260,12311,1,2659041,NaN,2020-02-20 19:40:00,0,0,Thursday
174,2020-02-20,KLK,13260,12311,39,2658088,2020-02-22 04:35:00,NaN,1714,2,Thursday
175,2020-02-20,HWH,11628,12321,1,2659041,NaN,2020-02-20 21:55:00,0,0,Thursday
222,2020-02-20,CSMT,11628,12321,48,10448787,2020-02-22 11:25:00,NaN,2159,2,Thursday
223,2020-02-20,NDLS,11849,12616,1,2657756,NaN,2020-02-20 18:40:00,0,0,Thursday
261,2020-02-20,MAS,11849,12616,39,2658933,2020-02-22 06:20:00,NaN,2182,2,Thursday
262,2020-02-20,ERS,11850,12617,1,2659585,NaN,2020-02-20 10:50:00,0,0,Thursday
309,2020-02-20,NZM,11850,12617,48,2657830,2020-02-22 13:15:00,NaN,2761,2,Thursday
310,2020-02-20,TVC,11858,12625,1,2657792,NaN,2020-02-20 11:15:00,0,0,Thursday
352,2020-02-20,NDLS,11858,12625,43,2657756,2020-02-22 13:45:00,NaN,3031,2,Thursday
353,2020-02-20,MAS,11889,12656,1,2658933,NaN,2020-02-20 09:35:00,0,0,Thursday
396,2020-02-20,ADI,11889,12656,44,2657971,2020-02-21 18:30:00,NaN,1892,1,Thursday
397,2020-02-20,NZM,11953,12722,1,2657830,NaN,2020-02-20 23:00:00,0,0,Thursday
443,2020-02-20,HYB,11953,12722,47,2659066,2020-02-22 04:45:00,NaN,1670,2,Thursday
444,2020-02-20,CSMT,12016,12809,1,10448787,NaN,2020-02-20 20:35:00,0,0,Thursday
487,2020-02-20,HWH,12016,12809,44,2659041,2020-02-22 05:50:00,NaN,1963,2,Thursday
488,2020-02-20,ADI,12038,12833,1,2657971,NaN,2020-02-20 00:15:00,0,0,Thursday
550,2020-02-20,HWH,12038,12833,63,2659041,2020-02-21 13:30:00,NaN,2086,1,Thursday
551,2020-02-19,HWH,12039,12834,1,2659041,NaN,2020-02-19 23:55:00,0,0,Wednesday
614,2020-02-19,ADI,12039,12834,64,2657971,2020-02-21 13:25:00,NaN,2086,2,Wednesday
615,2020-02-20,MAS,12045,12840,1,2658933,NaN,2020-02-20 23:45:00,0,0,Thursday
650,2020-02-20,HWH,12045,12840,36,2659041,2020-02-22 04:00:00,NaN,1663,2,Thursday
651,2020-02-20,BDTS,12117,12925,1,2658361,NaN,2020-02-20 12:00:00,0,0,Thursday
688,2020-02-20,KLK,12117,12925,38,2658088,2020-02-21 16:45:00,NaN,1676,1,Thursday
694,2020-02-20,ASR,12117,12925,44,2657719,2020-02-21 19:20:00,NaN,1823,1,Thursday

In [197]:
test_df['runDate']= pd.to_datetime(test_df['runDate'])
test_df['scheduledArrival']= pd.to_datetime(test_df['scheduledArrival'])
test_df['scheduledDeparture']= pd.to_datetime(test_df['scheduledDeparture'])

In [198]:
test_df['scheduledArrival'] = test_df[['scheduledArrival','scheduledDeparture']].apply(lambda x:correct_scheduled_arrival(x),axis=1)

In [199]:
test_df['trainCode'] = test_df['trainCode'].apply(lambda x: "T-"+str(x))

In [200]:
test_df

,runDate,stations,trainId,trainCode,index,trainStationId,scheduledArrival,scheduledDeparture,distance,dayCount,day
0,2020-02-20,FZR,11528,T-12138,1,2657812,NaT,2020-02-20 21:40:00,0,0,Thursday
1,2020-02-20,FDK,11528,T-12138,2,2659393,2020-02-20 22:05:00,2020-02-20 22:07:00,32,0,Thursday
2,2020-02-20,KKP,11528,T-12138,3,2658108,2020-02-20 22:23:00,2020-02-20 22:25:00,45,0,Thursday
3,2020-02-20,GJUT,11528,T-12138,4,2734206,2020-02-20 22:38:00,2020-02-20 22:40:00,61,0,Thursday
4,2020-02-20,GNA,11528,T-12138,5,2742572,2020-02-20 22:54:00,2020-02-20 22:56:00,76,0,Thursday
...,...,...,...,...,...,...,...,...,...,...,...
690,2020-02-20,PGW,12117,T-12925,40,2658284,2020-02-21 17:19:00,2020-02-21 17:21:00,1723,1,Thursday
691,2020-02-20,JRC,12117,T-12925,41,2657701,2020-02-21 17:37:00,2020-02-21 17:39:00,1739,1,Thursday
692,2020-02-20,JUC,12117,T-12925,42,2657676,2020-02-21 17:53:00,2020-02-21 17:58:00,1744,1,Thursday
693,2020-02-20,BEAS,12117,T-12925,43,2658299,2020-02-21 18:30:00,2020-02-21 18:32:00,1780,1,Thursday
694,2020-02-20,ASR,12117,T-12925,44,2657719,2020-02-21 19:20:00,NaT,1823,1,Thursday

In [201]:
test_df['scheduledArrival'] = test_df[['scheduledArrival','runDate','dayCount']].apply(lambda x: null_value_imputation(x),axis=1)

test_df['scheduledDeparture'] = test_df[['scheduledDeparture','runDate','dayCount']].apply(lambda x: null_value_imputation(x),axis=1)

In [202]:
test_df['scheduledArrival_delta'] =  (test_df['scheduledArrival']-test_df['runDate']).apply(lambda x: x.total_seconds() / 60)
test_df['scheduledDeparture_delta'] =  (test_df['scheduledDeparture']-test_df['runDate']).apply(lambda x: x.total_seconds() / 60)

In [203]:
test_df.trainCode.unique()

array(['T-12138', 'T-12139', 'T-12295', 'T-12311', 'T-12321', 'T-12616',
       'T-12617', 'T-12625', 'T-12656', 'T-12722', 'T-12809', 'T-12833',
       'T-12834', 'T-12840', 'T-12925'], dtype=object)

In [204]:
test_df["trainCode"] = test_df["trainCode"].apply(lambda x: trainCode_encoding[x])

In [205]:
test_df["stations"] = test_df["stations"].apply(lambda x: stations_encoding[x])

In [206]:
feature_cols = ['stations', 'trainCode', 'distance', 'dayCount','scheduledArrival_delta', 'scheduledDeparture_delta']

In [207]:
test_df[feature_cols]

,stations,trainCode,distance,dayCount,scheduledArrival_delta,scheduledDeparture_delta
0,1,1,0,0,0.0,1300.0
1,2,1,32,0,1325.0,1327.0
2,3,1,45,0,1343.0,1345.0
3,4,1,61,0,1358.0,1360.0
4,5,1,76,0,1374.0,1376.0
...,...,...,...,...,...,...
690,344,15,1723,1,2479.0,2481.0
691,345,15,1739,1,2497.0,2499.0
692,346,15,1744,1,2513.0,2518.0
693,347,15,1780,1,2550.0,2552.0
694,348,15,1823,1,2600.0,1440.0

In [208]:
arrival_delay = arrival_xgb.predict(test_df[feature_cols])

In [209]:
test_df['arrival_delay'] = arrival_delay

In [210]:
test_df

,runDate,stations,trainId,trainCode,index,trainStationId,scheduledArrival,scheduledDeparture,distance,dayCount,day,scheduledArrival_delta,scheduledDeparture_delta,arrival_delay
0,2020-02-20,1,11528,1,1,2657812,2020-02-20 00:00:00,2020-02-20 21:40:00,0,0,Thursday,0.0,1300.0,2.120655
1,2020-02-20,2,11528,1,2,2659393,2020-02-20 22:05:00,2020-02-20 22:07:00,32,0,Thursday,1325.0,1327.0,9.253135
2,2020-02-20,3,11528,1,3,2658108,2020-02-20 22:23:00,2020-02-20 22:25:00,45,0,Thursday,1343.0,1345.0,9.664788
3,2020-02-20,4,11528,1,4,2734206,2020-02-20 22:38:00,2020-02-20 22:40:00,61,0,Thursday,1358.0,1360.0,11.350401
4,2020-02-20,5,11528,1,5,2742572,2020-02-20 22:54:00,2020-02-20 22:56:00,76,0,Thursday,1374.0,1376.0,12.190215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690,2020-02-20,344,12117,15,40,2658284,2020-02-21 17:19:00,2020-02-21 17:21:00,1723,1,Thursday,2479.0,2481.0,17.445448
691,2020-02-20,345,12117,15,41,2657701,2020-02-21 17:37:00,2020-02-21 17:39:00,1739,1,Thursday,2497.0,2499.0,19.639807
692,2020-02-20,346,12117,15,42,2657676,2020-02-21 17:53:00,2020-02-21 17:58:00,1744,1,Thursday,2513.0,2518.0,18.383123
693,2020-02-20,347,12117,15,43,2658299,2020-02-21 18:30:00,2020-02-21 18:32:00,1780,1,Thursday,2550.0,2552.0,19.019814
694,2020-02-20,348,12117,15,44,2657719,2020-02-21 19:20:00,2020-02-21 00:00:00,1823,1,Thursday,2600.0,1440.0,23.247057

In [211]:
departure_delay = delay_xgb.predict(test_df[feature_cols])

In [212]:
test_df['departure_delay'] = departure_delay

In [214]:
test_df.to_csv('Arnav_.csv',index=False)